package com.cmcc.vrp.province.dao;

import com.cmcc.vrp.province.model.SdAccountChargeRecord;
/**
 * 
 * @ClassName: SdAccountChargeRecordMapper 
 * @Description: 山东账户接口报文记录
 * @author: Rowe
 * @date: 2017年9月4日 下午3:44:49
 */
public interface SdAccountChargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    int insert(SdAccountChargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    int insertSelective(SdAccountChargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    SdAccountChargeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdAccountChargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_account_charge_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdAccountChargeRecord record);
}