package com.cmcc.vrp.util;

/**
 * 全局配置key的枚举类 <p> Created by sunyiwei on 2016/7/22.
 */
public enum GlobalConfigKeyEnum {
    //平台登录URL
    LOGIN_URL("LOGIN_URL", "平台登录URL"),

    PLATFORM_URL("PLATFORM_URL", "平台域名"),

    //平台登录短信发送频率限制
    LOGIN_SMS_LIMIT("LOGIN_SMS_LIMIT", "平台登录短信发送频率限制"),

    //漫道短信相关的配置信息
    MD_URL("MD_URL", "漫道短信的请求地址"),
    MD_SN("MD_SN", "漫道短信的请求序列号"),
    MD_PWD("MD_PWD", "漫道短信的请求密码"),
    MD_SIGN("MD_SIGN", "漫道短信的签名"),

    //四川短信配置信息
    SC_MSG_TEMPLATE_ID1("SC_MSG_TEMPLATE_ID1", "四川短信模板1"),
    SC_MSG_TEMPLATE_ID2("SC_MSG_TEMPLATE_ID2", "四川短信模板2"),
    SC_MSG_TEMPLATE_ID3("SC_MSG_TEMPLATE_ID3", "四川短信模板3"),
    SC_MSG_SEND_URL("SC_MSG_SEND_URL", "四川短信发送URL"),
    SC_MSG_APPID("SC_MSG_APPID", "四川短信appId"),
    SC_MSG_APPKEY("SC_MSG_APPKEY", "四川短信appKey"),
    SC_MSG_PRIVATE_KEY("SC_MSG_PRIVATE_KEY", "四川短信私钥"),
    SC_MSG_METHOD("SC_MSG_METHOD", "四川短信方法名"),
    SC_MSG_VERSION("SC_MSG_VERSION", "四川短信协议版本"),
    SC_MSG_ENV("SC_MSG_ENV", "四川短信环境"),
    SC_MSG_SECRET("SC_MSG_SECRET", "四川短信密钥"),
    
    //开放平台短信设置
    OPEN_PLATFORM_SMS_APIKEY("OPEN_PLATFORM_SMS_APIKEY","开放平台短信APIKEY"),
    OPEN_PLATFORM_SMS_APPSECRET("OPEN_PLATFORM_SMS_APPSECRET","开放平台短信APPSECRET"),
    OPEN_PLATFORM_SMS_MESSAGESIGN("OPEN_PLATFORM_SMS_MESSAGESIGN","开放平台短信短信内容签名"),
    OPEN_PLATFORM_SMS_SENDURL("OPEN_PLATFORM_SMS_SENDURL","开放平台短信地址"),
    OPEN_PLATFORM_SMS_TEMPLATEID("OPEN_PLATFORM_SMS_TEMPLATEID","开放平台短信模板Id"),

    //内蒙古BOSS配置
    BOSS_NM_APPID("BOSS_NM_APPID", "内蒙古BOSS的appId"),
    BOSS_NM_PUBKEY("BOSS_NM_PUBKEY", "内蒙古BOSS的pubKey"),
    BOSS_NM_BUSICODE_CHARGE("BOSS_NM_BUSICODE_CHARGE", "内蒙古BOSS的busiCodeCharge"),
    BOSS_NM_BUSICODE_SMS("BOSS_NM_BUSICODE_SMS", "内蒙古BOSS的busiCodeSms"),
    BOSS_NM_BUSICODE_QUERY("BOSS_NM_BUSICODE_QUERY", "内蒙古BOSS的busiCodeQuery"),
    BOSS_NM_CLIENT_IP("BOSS_NM_CLIENT_IP", "内蒙古BOSS的clientIP"),
    BOSS_NM_COUNTRY_CODE("BOSS_NM_COUNTRY_CODE", "内蒙古BOSS的countryCode"),
    BOSS_NM_REGION_CODE("BOSS_NM_REGION_CODE", "内蒙古BOSS的regionCode"),
    BOSS_NM_ACT_TYPE("BOSS_NM_ACT_TYPE", "内蒙古BOSS的actType"),
    BOSS_NM_BOSS_URL("BOSS_NM_BOSS_URL", "内蒙古BOSS的bossUrl"),

    //湖南BOSS配置

    BOSS_HUNAN_SECRET("BOSS_HUNAN_SECRET", "湖南BOSS的secret"),

    BOSS_HUNAN_LOCALE("BOSS_HUNAN_LOCALE", "湖南BOSS的本地化代码"),


    //湖南BOSS配置：20170302
    BOSS_HUNAN_URL("BOSS_HUNAN_URL", "湖南BOSS请求URL"),
    BOSS_HUNAN_FORMAT("BOSS_HUNAN_FORMAT", "湖南BOSS的响应格式：默认json"),
    BOSS_HUNAN_APPID("BOSS_HUNAN_APPID", "湖南BOSS的appId"),
    BOSS_HUNAN_ENV("BOSS_HUNAN_ENV", "湖南BOSS的环境"),
    BOSS_HUNAN_VERSION("BOSS_HUNAN_VERSION", "湖南BOSS的版本号"),

    BOSS_HUNAN_PROVINCE_CODE("BOSS_HUNAN_PROVINCE_CODE", "湖南BOSS省别编码"),
    BOSS_HUNAN_IN_MODE_CODE("BOSS_HUNAN_IN_MODE_CODE", "湖南BOSS接入方式"),
    BOSS_HUNAN_TRADE_EPARCHY_CODE("BOSS_HUNAN_TRADE_EPARCHY_CODE", "湖南BOSS地州编码"),
    BOSS_HUNAN_TRADE_CITY_CODE("BOSS_HUNAN_TRADE_CITY_CODE", "湖南BOSS业务区编码"),
    BOSS_HUNAN_TRADE_DEPART_ID("BOSS_HUNAN_TRADE_DEPART_ID", "湖南BOSS员工所在的部门"),
    BOSS_HUNAN_TRADE_STAFF_ID("BOSS_HUNAN_TRADE_STAFF_ID", "湖南BOSS员工编码"),
    BOSS_HUNAN_TRADE_DEPART_PASSWD("BOSS_HUNAN_TRADE_DEPART_PASSWD", "湖南BOSS渠道接入密码"),
    BOSS_HUNAN_TRADE_TERMINAL_ID("BOSS_HUNAN_TRADE_TERMINAL_ID", "湖南BOSS接入IP"),
    BOSS_HUNAN_ROUTE_EPARCHY_CODE("BOSS_HUNAN_ROUTE_EPARCHY_CODE", "湖南BOSS路由地州编码"),

    BOSS_HUNAN_PRODUCT_ID("BOSS_HUNAN_PRODUCT_ID", "湖南BOSS端的产品编码，特别说明：不同产品该值相同，产品通过资费编码进行区分，BOSS端的资费编码在平台存储为产品编码"),

    BOSS_HUNAN_CHARGE_METHOD("BOSS_HUNAN_CHARGE_METHOD","湖南BOSS的通用充值method"),
    BOSS_HUNAN_FREE_OF_CHARGE_METHOD("BOSS_HUNAN_FREE_OF_CHARGE_METHOD", "湖南BOSS免费流量池充值接口method"),
    BOSS_HUNAN_FREE_OF_DISCNT_METHOD("BOSS_HUNAN_FREE_OF_DISCNT_METHOD", "湖南BOSS免费流量池充值接口根据手机号码获取地市信息method"),
    BOSS_HUNAN_FREE_OF_MODIFY_TAG("BOSS_HUNAN_FREE_OF_MODIFY_TAG", "湖南BOSS免费流量池充值接口选择变更标记"),
    BOSS_HUNAN_FREE_OF_ELEMENT_TYPE_CODE("BOSS_HUNAN_FREE_OF_ELEMENT_TYPE_CODE", "湖南BOSS免费流量池充值接口元素类型"),
    
    BOSS_HUNAN_QUERY_GROUP_ACCOUNT_METHOD("BOSS_HUNAN_QUERY_GROUP_ACCOUNT_METHOD", "湖南BOSS的查询企业账户method"),
    BOSS_HUNAN_QUERY_GROUP_PRODUCT_METHOD("BOSS_HUNAN_QUERY_GROUP_PRODUCT_METHOD", "湖南BOSS的查询企业产品method"),
    BOSS_HUNAN_QUERY_TYPE("BOSS_HUNAN_QUERY_TYPE", "湖南BOSS查询企业产品列表时固定参数,TYPE=00"),
    
    //出账日设置
    CHECK_ACCOUNT_DATE_TYPE("CHECK_ACCOUNT_DATE_TYPE", "对账日类型"),
    CHECK_ACCOUNT_START_DAY("CHECK_ACCOUNT_START_DAY", "对账日开始日期"),
    CHECK_ACCOUNT_START_TIME("CHECK_ACCOUNT_START_TIME", "对账日开始时间"),
    CHECK_ACCOUNT_END_DAY("CHECK_ACCOUNT_END_DAY", "对账日结束日期"),
    CHECK_ACCOUNT_END_TIME("CHECK_ACCOUNT_END_TIME", "对账日结束时间"),

    //JWT签名
    JWT_SIGN_PREFIX("JWT_SIGN_PREFIX", "JWT_TOKEN生成签名时的前缀"),
    JWT_SIGN_SUFFIX("JWT_SIGN_SUFFIX", "JWT_TOKEN生成签名时的后缀"),

    //接口认证
    TOKEN_VALID_PERIOD("TOKEN_VALID_PERIOD", "接口认证的有效时间，以分钟为单位"),

    //重庆BOSS
    BOSS_CQ_HOST("BOSS_CQ_HOST", "重庆BOSS地址"),
    BOSS_CQ_PORT("BOSS_CQ_PORT", "重庆BOSS端口"),

    //山东新BOSS
    BOSS_SD_EC_APPKEY("BOSS_SD_EC_APPKEY", "山东BOSS的EC接口appkey"),
    BOSS_SD_EC_APPSECRET("BOSS_SD_EC_APPSECRET", "山东BOSS的EC接口appsecret"),
    BOSS_SD_EC_CHARGE_URL("BOSS_SD_EC_CHARGE_URL", "山东BOSS的EC接口CHARGE_URL"),
    BOSS_SD_EC_AUTH_URL("BOSS_SD_EC_AUTH_URL", "山东BOSS的EC接口AUTH_URL"),


    //山东旧BOSS
    BOSS_SD_APPKEY("BOSS_SD_APPKEY", "山东BOSS的appkey"),
    BOSS_SD_APPSECRET("BOSS_SD_APPSECRET", "山东BOSS的appsecret"),
    BOSS_SD_USERID("BOSS_SD_USERID", "山东BOSS的userId"),
    BOSS_SD_ORDER_URL("BOSS_SD_ORDER_URL", "山东BOSS的appsecret"),

    //PLUS平台的河南BOSS渠道
    BOSS_HENAN_GBILL_ID("BOSS_HENAN_GBILL_ID", "河南BOSS的GBILL_ID"),
    BOSS_HENAN_SMS_TEMPLATE("BOSS_HENAN_SMS_TEMPLATE", "河南BOSS的smsTemplate"),
    BOSS_HENAN_VALID_TYPE("BOSS_HENAN_VALID_TYPE", "河南BOSS的validType"),
    BOSS_HENAN_VALID_MONTH("BOSS_HENAN_VALID_MONTH", "河南BOSS的validMonth"),
    BOSS_HENAN_APPID("BOSS_HENAN_APPID", "河南BOSS的appId"),
    BOSS_HENAN_APPKEY("BOSS_HENAN_APPKEY", "河南BOSS的appKey"),
    BOSS_HENAN_ZYHY_ENTID("BOSS_HENAN_ZYHY_ENTID", "Plus平台中代理企业的ID"),

    //河南BOSS公共部分
    BOSS_HENAN_CHARGE_DOMAIN("BOSS_HENAN_CHARGE_DOMAIN", "河南BOSS的ChargeDomain"),
    BOSS_HENAN_AUTH_DOMAIN("BOSS_HENAN_AUTH_DOMAIN", "河南BOSS的authDomain"),
    BOSS_HENAN_QUERY_FLAG("BOSS_HENAN_QUERY_FLAG", "河南BOSS的查询充值状态标志"),
    BOSS_HENAN_DECODE_KEY("BOSS_HENAN_DECODE_KEY", "河南BOSS回调包体解密KEY"),

    //河南省流量平台的河南BOSS渠道
    BOSS_HENAN_PLATFORM_SMS_TEMPLATE("BOSS_HENAN_PLATFORM_SMS_TEMPLATE", "河南平台侧BOSS的smsTemplate"),
    BOSS_HENAN_PLATFORM_VALID_TYPE("BOSS_HENAN_PLATFORM_VALID_TYPE", "河南平台侧BOSS的validType"),
    BOSS_HENAN_PLATFORM_VALID_MONTH("BOSS_HENAN_PLATFORM_VALID_MONTH", "河南平台侧BOSS的validMonth"),
    BOSS_HENAN_PLATFORM_APPID("BOSS_HENAN_PLATFORM_APPID", "河南平台侧BOSS的appId"),
    BOSS_HENAN_PLATFORM_APPKEY("BOSS_HENAN_PLATFORM_APPKEY", "河南平台侧BOSS的appKey"),

    //黑龙江BOSS充值接口--参数列表（直接与BOSS对接）    
    BOSS_HLJ_WSDL_ADDRESS("BOSS_HLJ_WSDL_ADDRESS", "黑龙江BOSS的WSDL地址"),
    BOSS_HLJ_CHARGE_ADDRESS("BOSS_HLJ_CHARGE_ADDRESS", "黑龙江BOSS的充值地址"),
    BOSS_HLJ_CHANNEL_SOURCE("BOSS_HLJ_CHANNEL_SOURCE", "黑龙江BOSS的渠道标识"),
    BOSS_HLJ_OP_CODE("BOSS_HLJ_OP_CODE", "黑龙江BOSS的操作代码"),
    BOSS_HLJ_LOGIN_NO("BOSS_HLJ_LOGIN_NO", "黑龙江BOSS的操作工号"),
    BOSS_HLJ_LOGIN_PWD("BOSS_HLJ_LOGIN_PWD", "黑龙江BOSS的操作密码"),
    BOSS_HLJ_PHONE_NO("BOSS_HLJ_PHONE_NO", "黑龙江BOSS的号码"),       
    BOSS_HLJ_IREPEAT_FLAG("BOSS_HLJ_IREPEAT_FLAG", "黑龙江BOSS批量充值接口之是否允许重复号码"),
    
    BOSS_HLJ_USE_BOSS_CHARGE_SINGLE_OR_BATCH("BOSS_HLJ_CHARGE_SINGLE_OR_BATCH", "黑龙江BOSS充值接口单个充值接口or批量充值接口"),
    BOSS_HLJ_USE_BOSS_INTERFACE("BOSS_HLJ_USE_BOSS_INTERFACE", "黑龙江BOSS充值接口是否直接对接BOSS接口"),
    
    //黑龙江充值结果查询接口--参数列表（直接与BOSS对接）
    BOSS_HLJ_QUERY_CHARGE_RESULT_WSDL("BOSS_HLJ_QUERY_CHARGE_RESULT_WSDL","黑龙江BOSS充值结果查询之WSDL地址"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_ADDRESS("BOSS_HLJ_QUERY_CHARGE_RESULT_ADDRESS","黑龙江BOSS充值结果查询之查询接口地址"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_ROWNUM("BOSS_HLJ_QUERY_CHARGE_RESULT_ROWNUM", "黑龙江BOSS充值结果查询之查询行数"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_ROWCOUNT("BOSS_HLJ_QUERY_CHARGE_RESULT_ROWCOUNT", "黑龙江BOSS充值结果查询之每行展示的个数"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_IOPPHONE("BOSS_HLJ_QUERY_CHARGE_RESULT_IOPPHONE", "黑龙江BOSS充值结果查询之操作员手机号"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_IUSERPWD("BOSS_HLJ_QUERY_CHARGE_RESULT_IUSERPWD", "黑龙江BOSS充值结果查询之用户密码"),
    BOSS_HLJ_QUERY_CHARGE_RESULT_IOPCODE("BOSS_HLJ_QUERY_CHARGE_RESULT_IOPCODE", "黑龙江BOSS充值结果查询之操作代码"),

    //黑龙江话费相关接口--参数列表
    BOSS_HLJ_FEE_PREPAY_QUERY("BOSS_HLJ_FEE_PREPAY_QUERY", "黑龙江话费红包账户可转预存查询api"),
    BOSS_HLJ_FEE_GROUP_PERSON("BOSS_HLJ_FEE_GROUP_PERSON", "黑龙江话费集团产品为个人充值API"),
    BOSS_HLJ_FEE_BALANCE_QUERY("BOSS_HLJ_FEE_BALANCE_QUERY", "黑龙江话费信息查询API"),
    BOSS_HLJ_FEE_ELECTRONIC_COUPON("BOSS_HLJ_FEE_ELECTRONIC_COUPON", "黑龙江话费红包电子券业务冲正API"),
    BOSS_HLJ_FEE_PRIVATE_KEY("BOSS_HLJ_FEE_PRIVATE_KEY", "黑龙江话费BOSS私钥路径"),
    BOSS_HLJ_FEE_APPKEY("BOSS_HLJ_FEE_APPKEY", "黑龙江BOSS话费接口之appKey"),
    BOSS_HLJ_FEE_GROUP_ACC_NO("BOSS_HLJ_FEE_GROUP_ACC_NO", "黑龙江BOSS话费接口之groupAccNo"),
    BOSS_HLJ_FEE_PHONE_NO("BOSS_HLJ_FEE_PHONE_NO", "黑龙江BOSS话费接口之phoneNo"),
    BOSS_HLJ_FEE_ACC_NBR("BOSS_HLJ_FEE_ACC_NBR", "黑龙江BOSS话费接口之accNbr"),
    BOSS_HLJ_FEE_GROUP_NO("BOSS_HLJ_FEE_GROUP_NO", "黑龙江BOSS话费接口之groupNo"),
    
    //黑龙江斯特奇营销卡充值接口--参数列表
    BOSS_HLJ_MDRC_CHARGE_URL("BOSS_HLJ_MDRC_CHARGE_URL", "思特奇流量卡充值URL"),

    //黑龙江斯特奇集团可赠送流量查询接口--参数列表
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_URL("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_URL", "黑龙江斯特奇集团可赠送流量查询接口之URL"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPRID("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPRID", "黑龙江斯特奇集团可赠送流量查询接口之操作工号"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPRROLE("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPRROLE", "黑龙江斯特奇集团可赠送流量查询接口之工号角色"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PASSWORD("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PASSWORD", "黑龙江斯特奇集团可赠送流量查询接口之工号密码"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PHONENUM("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PHONENUM", "黑龙江斯特奇集团可赠送流量查询接口之集团联系人联系电话"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_GROUPID("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_GROUPID", "黑龙江斯特奇集团可赠送流量查询接口之工号归属"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_LOGINNO("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_LOGINNO", "黑龙江斯特奇集团可赠送流量查询接口之工号"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPCODE("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_OPCODE", "黑龙江斯特奇集团可赠送流量查询接口之操作代码"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PROVINCEID("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PROVINCEID", "黑龙江斯特奇集团可赠送流量查询接口之省份代码"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_CHANNELID("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_CHANNELID", "黑龙江斯特奇集团可赠送流量查询接口之渠道标识"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PROVINCEGROUP("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_PROVINCEGROUP", "黑龙江斯特奇集团可赠送流量查询接口之省份组"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_ROUTEKEY("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_ROUTEKEY", "黑龙江斯特奇集团可赠送流量查询接口之路由类型"),
    BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_ROUTEVALUE("BOSS_HLJ_SITECH_QUERY_GROUP_ACCOUNT_ROUTEVALUE", "黑龙江斯特奇集团可赠送流量查询接口之路由值"),

    //黑龙江思特奇行业应用流量包实时赠送接口--参数列表
    BOSS_HLJ_SITECH_CHARGE_IS_ASYC("BOSS_HLJ_SITECH_CHARGE_IS_ASYC", "黑龙江斯特奇行业应用流量包实时赠送接口是否是异步方式"),
    BOSS_HLJ_SITECH_CHARGE_URL("BOSS_HLJ_SITECH_CHARGE_URL", "黑龙江斯特奇行业应用流量包实时赠送接口之URL"),
    BOSS_HLJ_SITECH_CHARGE_ACCESSTYPE("BOSS_HLJ_SITECH_CHARGE_ACCESSTYPE", "黑龙江斯特奇行业应用流量包实时赠送接口之赠送方式"),
    BOSS_HLJ_SITECH_CHARGE_EFFRULE("BOSS_HLJ_SITECH_CHARGE_EFFRULE", "黑龙江斯特奇行业应用流量包实时赠送接口之生效规则"),
    BOSS_HLJ_SITECH_CHARGE_EFFTIME("BOSS_HLJ_SITECH_CHARGE_EFFTIME", "黑龙江斯特奇行业应用流量包实时赠送接口之生效时间"),
    BOSS_HLJ_SITECH_CHARGE_EXPRULE("BOSS_HLJ_SITECH_CHARGE_EXPRULE", "黑龙江斯特奇行业应用流量包实时赠送接口之失效规则"),
    BOSS_HLJ_SITECH_CHARGE_EXPTIME("BOSS_HLJ_SITECH_CHARGE_EXPTIME", "黑龙江斯特奇行业应用流量包实时赠送接口之失效时间"),
    BOSS_HLJ_SITECH_CHARGE_PAYMODE("BOSS_HLJ_SITECH_CHARGE_PAYMODE", "黑龙江斯特奇行业应用流量包实时赠送接口之PAY_MODE"),
    BOSS_HLJ_SITECH_CHARGE_SALENUM("BOSS_HLJ_SITECH_CHARGE_SALENUM", "黑龙江斯特奇行业应用流量包实时赠送接口之SALE_NUM"),
    BOSS_HLJ_SITECH_CHARGE_SALEPRICE("BOSS_HLJ_SITECH_CHARGE_SALEPRICE", "黑龙江斯特奇行业应用流量包实时赠送接口之SALE_PRICE"),
    BOSS_HLJ_SITECH_CHARGE_SALESIZE("BOSS_HLJ_SITECH_CHARGE_SALESIZE", "黑龙江斯特奇行业应用流量包实时赠送接口之SALE_SIZE"),
    BOSS_HLJ_SITECH_CHARGE_OPERCODE("BOSS_HLJ_SITECH_CHARGE_OPERCODE", "黑龙江斯特奇行业应用流量包实时赠送接口之OPER_CODE"),
    BOSS_HLJ_SITECH_CHARGE_OPRID("BOSS_HLJ_SITECH_CHARGE_OPRID", "黑龙江斯特奇行业应用流量包实时赠送接口之OPR_ID"),
    BOSS_HLJ_SITECH_CHARGE_OPRROLE("BOSS_HLJ_SITECH_CHARGE_OPRROLE", "黑龙江斯特奇行业应用流量包实时赠送接口之OPR_ROLE"),
    BOSS_HLJ_SITECH_CHARGE_PASSWORD("BOSS_HLJ_SITECH_CHARGE_PASSWORD", "黑龙江斯特奇行业应用流量包实时赠送接口之PASS_WORD"),
    BOSS_HLJ_SITECH_CHARGE_PHONENUM("BOSS_HLJ_SITECH_CHARGE_PHONENUM", "黑龙江斯特奇行业应用流量包实时赠送接口之PHONE_NUM"),
    BOSS_HLJ_SITECH_CHARGE_UNITIDNO("BOSS_HLJ_SITECH_CHARGE_UNITIDNO", "黑龙江斯特奇行业应用流量包实时赠送接口之UNIT_ID_NO"),
    BOSS_HLJ_SITECH_CHARGE_REPEATEFLAG("BOSS_HLJ_SITECH_CHARGE_REPEATEFLAG", "黑龙江斯特奇行业应用流量包实时赠送接口之REPEAT_FLAG"),   
    BOSS_HLJ_SITECH_CHARGE_GROUPID("BOSS_HLJ_SITECH_CHARGE_GROUPID", "黑龙江斯特奇行业应用流量包实时赠送接口之GROUP_ID"),
    BOSS_HLJ_SITECH_CHARGE_LOGINNO("BOSS_HLJ_SITECH_CHARGE_LOGINNO", "黑龙江斯特奇行业应用流量包实时赠送接口之LOGIN_NO"),
    BOSS_HLJ_SITECH_CHARGE_OPCODE("BOSS_HLJ_SITECH_CHARGE_OPCODE", "黑龙江斯特奇行业应用流量包实时赠送接口之OP_CODE"),
    BOSS_HLJ_SITECH_CHARGE_PROVINCEID("BOSS_HLJ_SITECH_CHARGE_PROVINCEID", "黑龙江斯特奇行业应用流量包实时赠送接口之PROVINCE_ID"),
    BOSS_HLJ_SITECH_CHARGE_PROVICEGROUP("BOSS_HLJ_SITECH_CHARGE_PROVICEGROUP", "黑龙江斯特奇行业应用流量包实时赠送接口之PROVINCE_GROUP"),
    BOSS_HLJ_SITECH_CHARGE_CHANNELID("BOSS_HLJ_SITECH_CHARGE_CHANNELID", "黑龙江斯特奇行业应用流量包实时赠送接口之CHANNEL_ID"),
    BOSS_HLJ_SITECH_CHARGE_ROUTEKEY("BOSS_HLJ_SITECH_CHARGE_ROUTEKEY", "黑龙江斯特奇行业应用流量包实时赠送接口之ROUTE_KEY"),
    BOSS_HLJ_SITECH_CHARGE_ROUTEVALUE("BOSS_HLJ_SITECH_CHARGE_ROUTEVALUE", "黑龙江斯特奇行业应用流量包实时赠送接口之ROUTE_VALUE"),

    //甘肃BOSS
    BOSS_GS_PRODUCT_URL("BOSS_GS_PRODUCT_URL", "甘肃BOSS产品受理URL"),
    BOSS_GS_DYNAMIC_TOKEN_URL("BOSS_GS_DYNAMIC_TOKEN_URL", "甘肃BOSS动态鉴权服务URL"),
    BOSS_GS_VERSION("BOSS_GS_VERSION", "甘肃BOSS能力平台Version"),
    BOSS_GS_TEST_FLAG("BOSS_GS_TEST_FLAG", "甘肃BOSS测试标识"),
    BOSS_GS_APPID("BOSS_GS_APPID", "甘肃BOSS的appId"),
    BOSS_GS_ACCESS_TOKEN("BOSS_GS_ACCESS_TOKEN", "甘肃BOSS的accessToken"),
    BOSS_GS_USER_AUTHORIZATION_CODE("BOSS_GS_USER_AUTHORIZATION_CODE", "甘肃BOSS的userAuthorizationCode"),
    BOSS_GS_VALID_TYPE("BOSS_GS_VALID_TYPE", "甘肃BOSS的validType"),
    BOSS_GS_NEW_PLAN_ID("BOSS_GS_NEW_PLAN_ID", "甘肃BOSS的newPlanId"),
    BOSS_GS_NEW_BRAND("BOSS_GS_NEW_BRAND", "甘肃BOSS的newBrand"),
    BOSS_GS_PROD_TYPE("BOSS_GS_PROD_TYPE", "甘肃BOSS的prodType"),
    BOSS_GS_ACTION_TYPE("BOSS_GS_ACTION_TYPE", "甘肃BOSS的actionType"),
    BOSS_GS_BUS_TYPE("BOSS_GS_BUS_TYPE", "甘肃BOSS的busType"),
    BOSS_GS_SERVICE_ID("BOSS_GS_SERVICE_ID", "甘肃BOSS的serviceId"),
    BOSS_GS_PRE_PRODID("BOSS_GS_PRE_PRODID", "甘肃BOSS的preProdId"),
    BOSS_GS_VETYPE("BOSS_GS_VETYPE", "甘肃BOSS的veType"),
    BOSS_GS_EXPIRED_TIME("BOSS_GS_EXPIRED_TIME", "甘肃BOSS的验证码失效时间"),
    //四川BOSS
    BOSS_SC_ADD_MEMBER_URL("BOSS_SC_ADD_MEMBER_URL", "四川BOSS增加成员URL"),
    BOSS_SC_OPEN_URL("BOSS_SC_OPEN_URL", "四川BOSS流量统付开户URL"),
    BOSS_SC_PRIVATE_KEY_PATH("BOSS_SC_PRIVATE_KEY_PATH", "四川BOSS私钥路径"),
    BOSS_SC_USER_NAME("BOSS_SC_USER_NAME", "四川BOSS用户名"),
    BOSS_SC_APP_KEY("BOSS_SC_APP_KEY", "四川BOSS的appKey"),
    BOSS_SC_LOGIN_NO("BOSS_SC_LOGIN_NO", "四川BOSS登录账号"),
    BOSS_SC_OPEN_REGIONID("BOSS_SC_OPEN_REGIONID", "四川BOSS的regionId"),
    BOSS_SC_OPCODE("BOSS_SC_OPCODE", "四川BOSS的opCode"),
    BOSS_SC_OPEN_PRCID("BOSS_SC_OPEN_PRCID", "四川BOSS的prcId"),
    BOSS_SC_EXPIRE_RULE("BOSS_SC_EXPIRE_RULE", "四川BOSS的expireRule"),
    BOSS_SC_CANCEL_URL("BOSS_SC_CANCEL_URL", "四川BOSS的产品注销URL"),
    BOSS_SC_CANCEL_OPCODE("BOSS_SC_CANCEL_OPCODE", "四川BOSS的产品注销操作代码"),
    BOSS_SC_DEL_MEMBER_URL("BOSS_SC_DEL_MEMBER_URL", "四川BOSS的成员删除URL"),
    BOSS_SC_BALANCE_URL("BOSS_SC_BALANCE_URL", "四川BOSS的余额查询URL"),
    BOSS_SC_BALANCE_MSG_FLAG("BOSS_SC_BALANCE_MSG_FLAG", "四川BOSS余额查询下发短信标识"),
    BOSS_SC_APPQRY_URL("BOSS_SC_APPQRY_URL", "四川个人流量余额查询URL"),
    BOSS_SC_FLOWREDPACKET_URL("BOSS_SC_FLOWREDPACKET_URL", "四川BOSS流量红包的地址"),
    BOSS_SC_ORDERFLOW_URL("BOSS_SC_ORDERFLOW_URL", "四川BOSS附加资费订购地址"),
    BOSS_SC_FLOWREDPACKET_PRCID("BOSS_SC_FLOWREDPACKET_PRCID", "四川BOSS流量红包订购资费代码"),
    BOSS_SC_QRY_RANDPASS_URL("BOSS_SC_QRY_RANDPASS_URL", "四川BOSS随机码下发验证URL"),
    BOSS_SC_MEMBER_INQUIRY_URL("BOSS_SC_MEMBER_INQUIRY_URL", "四川BOSSv网成员查询URL"),


    //新疆BOSS
    BOSS_XJ_URL("BOSS_XJ_URL", "新疆boss地址"),
    BOSS_XJ_APPID("BOSS_XJ_APPID", "新疆bossAPPID"),
    BOSS_XJ_APPSECRET("BOSS_XJ_APPSECRET", "新疆bossAPPSECRET"),
    BOSS_XJ_PROVINCECODE("BOSS_XJ_PROVINCECODE", "新疆bossPROVINCECODE"),
    BOSS_XJ_TRADEEPARCHYCODE("BOSS_XJ_TRADEEPARCHYCODE", "新疆bossTRADEEPARCHYCODE"),
    BOSS_XJ_TRADESTAFFID("BOSS_XJ_TRADESTAFFID", "新疆bossTRADESTAFFID"),
    BOSS_XJ_TRADECITYCODE("BOSS_XJ_TRADECITYCODE", "新疆bossTRADECITYCODE"),
    BOSS_XJ_TRADEDEPARTID("BOSS_XJ_TRADEDEPARTID", "新疆bossTRADEDEPARTID"),
    BOSS_XJ_CHANNELTYPEID("BOSS_XJ_CHANNELTYPEID", "新疆bossCHANNELTYPEID"),
    BOSS_XJ_TRADEDEPARTNAME("BOSS_XJ_TRADEDEPARTNAME", "新疆bossTRADEDEPARTNAME"),
    BOSS_XJ_TRADESTAFFNAME("BOSS_XJ_TRADESTAFFNAME", "新疆bossTRADESTAFFNAME"),
    BOSS_XJ_TRADEDEPARTPASSWD("BOSS_XJ_TRADEDEPARTPASSWD", "新疆bossTRADEDEPARTPASSWD"),

    //自营平台
    BOSS_ZY_APP_KEY("BOSS_ZY_APP_KEY", "自营平台的appKey"),
    BOSS_ZY_APP_SECRET("BOSS_ZY_APP_SECRET", "自营平台的appSecret"),
    BOSS_ZY_AUTH_URL("BOSS_ZY_AUTH_URL", "自营平台的authUrl"),
    BOSS_ZY_CHARGE_URL("BOSS_ZY_CHARGE_URL", "自营平台的chargeUrl"),
    BOSS_ZY_QUERY_URL("BOSS_ZY_QUERY_URL", "自营平台的queryUrl"),

    //卓望BOSS
    BOSS_ZW_APP_KEY("BOSS_ZW_APP_KEY", "卓望BOSS的appKey"),
    BOSS_ZW_APP_SECRET("BOSS_ZW_APP_SECRET", "卓望BOSS的appSecret"),
    BOSS_ZW_TEST_FLAG("BOSS_ZW_TEST_FLAG", "卓望BOSS的testFlag"),
    BOSS_ZW_PRODUCT_ID("BOSS_ZW_PRODUCT_ID", "卓望BOSS的productId"),
    BOSS_ZW_URL("BOSS_ZW_URL", "卓望BOSS的充值地址"),

    //EC平台接口，自己接自己
    BOSS_EC_CQ_APP_KEY("BOSS_EC_CQ_APP_KEY", "重庆自营平台的appKey"),
    BOSS_EC_CQ_APP_SECRET("BOSS_EC_CQ_APP_SECRET", "重庆自营平台的appSecret"),
    BOSS_EC_CQ_AUTH_URL("BOSS_EC_CQ_AUTH_URL", "重庆自营平台的authUrl"),
    BOSS_EC_CQ_CHARGE_URL("BOSS_EC_CQ_CHARGE_URL", "重庆自营平台的chargeUrl"),
    BOSS_EC_PLUS_APP_KEY("BOSS_EC_PLUS_APP_KEY", "PLUS自营平台的appKey"),
    BOSS_EC_PLUS_APP_SECRET("BOSS_EC_PLUS_APP_SECRET", "PLUS自营平台的appSecret"),
    BOSS_EC_PLUS_AUTH_URL("BOSS_EC_PLUS_AUTH_URL", "PLUS自营平台的authUrl"),
    BOSS_EC_PLUS_CHARGE_URL("BOSS_EC_PLUS_CHARGE_URL", "PLUS自营平台的chargeUrl"),

    //双创接口
    SHUANCHANG_URL("SHUANCHANG_URL", "双创接口的请求URL"),
    SHUANCHANG_CODE("SHUANCHANG_CODE", "双创接口的请求CODE"),
    JIAKAI_URL("JIAKAI_URL", "家开接口的请求URL"),
    JIAKAI_CODE("JIAKAI_CODE", "家开接口的请求CODE"),

    //企业管理员授权模板
    TEMPLATE_FILE_NAME("TEMPLATE_FILE_NAME", "模板文件名称"),
    TEMPLATE_FILE_KEY("TEMPLATE_FILE_KEY", "模板文件KEY"),

    //首页的LOGO名称
    LOGO_NAME("LOGO_NAME", "首页的LOGO名称"),

    //手机号段
    PHONE_REGION_QUERY_URL("PHONE_REGION_QUERY_URL", "手机号段查询服务URL"),

    //省份标识
    PROVINCE_FLAG("PROVINCE_FLAG", "省份标识"),

    //S3相关的配置
    S3_AWS_ACCESS_KEY("S3_AWS_ACCESS_KEY", "S3的accessKey"),
    S3_AWS_ACCESS_SECRET("S3_AWS_ACCESS_SECRET", "S3的accessSecret"),
    S3_BUCKET_NAME("S3_BUCKET_NAME", "S3的bucketName"),
    S3_HOST("S3_HOST", "S3的HOST"),
    S3_PROTOCOL("S3_PROTOCOL", "连接S3使用的协议"),

    //营销卡相关的配置
    MDRC_GENERATE_AUTH_CODE("MDRC_GENERATE_AUTH_CODE", "营销卡制卡权限代码"),
    MDRC_DOWNLOAD_AUTH_CODE("MDRC_DOWNLOAD_AUTH_CODE", "营销卡下载权限代码"),
    MDRC_CARDMAKER_AUTH_CODE("MDRC_CARDMAKER_AUTH_CODE", "营销卡制卡商权限代码"),
    MDRC_TEMPLATE_AUTH_CODE("MDRC_TEMPLATE_AUTH_CODE", "营销卡模板权限代码"),
    MDRC_PROVINCE_CODE("MDRC_PROVINCE_CODE", "营销卡省份代码"),
    MDRC_TEMPLATE_FILE_PATH("MDRC_TEMPLATE_FILE_PATH", "营销卡模板文件存储目录"),
    MDRC_DATA_FILE_PATH("MDRC_DATA_FILE_PATH", "营销卡数据临时存储目录"),
    MDRC_ZIP_FILE_PATH("MDRC_ZIP_FILE_PATH", "营销卡打包文件临时存储目录"),
    MDRC_PURCHASE_DATA_FILE_PATH("MDRC_PURCHASE_DATA_FILE_PATH", "营销卡采购数据临时存储目录"),

    //营销活动相关的配置
    ACTIVITY_IS_AUTHORIZED_URL("ACTIVITY_IS_AUTHORIZED_URL", "判断活动是否授权的URL"),
    ACTIVITY_AUTHORIZED_URL("ACTIVITY_AUTHORIZED_URL", "活动授权的URL"),
    ACTIVITY_GENERATE_URL("ACTIVITY_GENERATE_URL", "生成活动的URL"),
    ACTIVITY_OFFLINE_URL("ACTIVITY_OFFLINE_URL", "下架活动的URL"),
    ACTIVITY_PLATFORM_NAME("ACTIVITY_PLATFORM_NAME", "生成活动的平台标识"),
    ACTIVITY_CALLBACK_URL("ACTIVITY_CALLBACK_URL", "活动的回调地址"),
    ACTIVITY_IMAGE_PATH("ACTIVITY_IMAGE_PATH", "活动图片存储目录"),
    ACTIVITY_RULE_TEMPLATE_FILE_PATH("ACTIVITY_RULE_TEMPLATE_FILE_PATH", "卡模板文件存放目录"),

    //对账相关的配置
    ACCOUNT_PATH("ACCOUNT_PATH", "账单存储的目录"),
    ACCOUNT_DIFF_PATH("ACCOUNT_DIFF_PATH", "存储账单差异的目录"),

    //角色相关的代码配置
    SUPER_ADMIN_ROLE_ID("SUPER_ADMIN_ROLE_ID", "超级管理员角色ID"),
    ACCOUNT_MANAGER_ROLE_ID("ACCOUNT_MANAGER_ROLE_ID", "客户经理角色ID"),
    ENTERPRISE_CONTACTOR_ROLE_ID("ENTERPRISE_CONTACTOR_ROLE_ID", "企业关键人角色ID"),
    FLOW_CARD_MANAGER_ROLE_ID("FLOW_CARD_MANAGER_ROLE_ID", "流量卡关键人角色ID"),
    CARD_MAKER_ROLE_ID("CARD_MAKER_ROLE_ID", "制卡商角色ID"),
    PROVINCE_MANAGER_ROLE_ID("PROVINCE_MANAGER_ROLE_ID", "省级管理员角色ID"),
    CITY_MANAGER_ROLE_ID("CITY_MANAGER_ROLE_ID", "市级管理员角色ID"),

    //浙江BOSS
    BOSS_ZJ_CHARGE_URL("BOSS_ZJ_CHARGE_URL", "浙江BOSS渠道充值URL"),
    BOSS_ZJ_CHARGE_APPKEY("BOSS_ZJ_CHARGE_APPKEY", "浙江BOSS渠道APPKEY"),
    BOSS_ZJ_CHARGE_APPSECRET("BOSS_ZH_CHARGE_APPSECRET", "浙江BOSS渠道APPSECRET"),
    BOSS_ZJ_CHARGE_BIZCODE("BOSS_ZJ_CHARGE_BIZCODE", "浙江BOSS渠道BIZCODE"),

    //北京BOSS
    BOSS_BJ_ADMIN_NAME("BOSS_BJ_ADMIN_NAME", "北京BOSS渠道ADMINNAME"),
    BOSS_BJ_CA("BOSS_BJ_CA", "北京BOSS渠道CA"),
    BOSS_BJ_PASSWORD("BOSS_BJ_PASSWORD", "北京BOSS渠道PASSWORD"),

    //上海BOSS
    BOSS_SHANGHAI_GIVEVALID("BOSS_SHANGHAI_GIVEVALID", "上海BOSS赠送有效期"),
    BOSS_SHANGHAI_ACCPERIODEFFRULE("BOSS_SHANGHAI_ACCPERIODEFFRULE", "上海BOSS成员账期生效规则"),
    BOSS_SHANGHAI_CHANNELTYPE("BOSS_SHANGHAI_CHANNELTYPE", "上海BOSS渠道编号"),
    BOSS_SHANGHAI_APPCODE("BOSS_SHANGHAI_APPCODE", "上海BOSS成员添加APPCODE"),
    BOSS_SHANGHAI_APK("BOSS_SHANGHAI_APK", "上海BOSS成员添加APK"),
    BOSS_SHANGHAI_APICODE("BOSS_SHANGHAI_APICODE", "上海BOSS成员添加APICODE"),
    BOSS_SHANGHAI_POSPECID("BOSS_SHANGHAI_POSPECID", "上海BOSS成员添加POSPECID"),

    //福建BOSS
    BOSS_FUJIAN_APPKEY("BOSS_FUJIAN_APPKEY", "福建BOSS通道APPKEY"),
    BOSS_FUJIAN_APPID("BOSS_FUJIAN_APPID", "福建BOSS通道APPID"),
    BOSS_FUJIAN_ECCODE("BOSS_FUJIAN_ECCODE", "福建BOSS通道ECCODE"),
    BOSS_FUJIAN_ORDER_URL("BOSS_FUJIAN_ORDER_URL", "福建BOSS通道ORDER_URL"),

    //广东BOSS
    BOSS_GUANGDONG_ECCODE("BOSS_GUANGDONG_ECCODE", "广东BOSS通道ECCODE"),
    BOSS_GUANGDONG_ECUSERNAME("BOSS_GUANGDONG_ECUSERNAME", "广东BOSS通道ECUSERNAME"),
    BOSS_GUANGDONG_ECPASSWORD("BOSS_GUANGDONG_ECPASSWORD", "广东BOSS通道ECPASSWORD"),
    BOSS_GUANGDONG_PRDORDNUM("BOSS_GUANGDONG_PRDORDNUM", "广东BOSS通道PRDORDNUM"),
    BOSS_GUANGDONG_CHARGE_URL("BOSS_GUANGDONG_CHARGE_URL", "广东BOSS通道CHARGEURL"),

    //河北BOSS
    BOSS_HEBEI_GROUPNO("BOSS_HEBEI_GROUPNO", "河北BOSS渠道集团编码"),
    BOSS_HEBEI_GRPSUBSID("BOSS_HEBEI_GRPSUBSID", "河北BOSS渠道产品编号"),
    BOSS_HEBEI_URL("BOSS_HEBEI_URL", "河北BOSS渠道充值地址"),
    BOSS_HEBEI_QUERY_URL("BOSS_HEBEI_QUERY_URL", "河北BOSS渠道查询地址"),

    //广西BOSS
    BOSS_GUANGXI_URL("BOSS_GUANGXI_URL", "广西BOSS渠道地址"),
    BOSS_GUANGXI_APPKEY("BOSS_GUANGXI_APPKEY", "广西BOSS渠道APPKEY"),
    BOSS_GUANGXI_APPSECRET("BOSS_GUANGXI_APPSECRET", "广西BOSS渠道APPSECRET"),
    BOSS_GUANGXI_PRODUCTID("BOSS_GUANGXI_PRODUCTID", "广西BOSS渠道PRODUCTID"),
    BOSS_GUANGXI_FLAG("BOSS_GUANGXI_FLAG", "广西BOSS渠道测试标记FLAG"),
    BOSS_GUANGXI_ACTIVITYCODE("BOSS_GUANGXI_ACTIVITYCODE", "广西BOSS渠道ACTIVITYCODE"),
    BOSS_GUANGXI_BIPCODE("BOSS_GUANGXI_BIPCODE", "广西BOSS渠道BIPCODE"),
    BOSS_GUANGXI_ACTIONCODE("BOSS_GUANGXI_ACTIONCODE", "广西BOSS渠道ACTIONCODE"),

    //陕西BOSS
    BOSS_SHANXI_CHARGE_URL("BOSS_SHANXI_CHARGE_URL", "陕西BOSS渠道充值地址"),
    BOSS_SHANXI_FEE_PRODUCT("BOSS_SHANXI_FEE_PRODUCT", "陕西话费包产品编码"),
    BOSS_SHANXI_TRADESTAFFID("BOSS_SHANXI_TRADESTAFFID", "陕西BOSS工号"),
    BOSS_SHANXI_INMODECODE("BOSS_SHANXI_INMODECODE", "陕西 BOSS接入方式"),
    BOSS_SHANXI_PASSWD("BOSS_SHANXI_PASSWD", "陕西 BOSS密码"),
    BOSS_SHANXI_ACTIVITY_TRADESTAFFID("BOSS_SHANXI_ACTIVITY_TRADESTAFFID", "陕西营销活动BOSS工号"),
    BOSS_SHANX_ACTIVITY_INMODECODE("BOSS_SHANX_ACTIVITY_INMODECODE", "陕西 营销活动BOSS接入方式"),

    BOSS_SHANXI_XQJ_CODE("BOSS_SHANXI_XQJ_CODE", "陕西寻秦迹企业编码"),
    BOSS_SHANXI_XQJ_TRADESTAFFID("BOSS_SHANXI_XQJ_TRADESTAFFID", "陕西BOSS寻秦迹工号"),
    BOSS_SHANXI_XQJ_INMODECODE("BOSS_SHANXI_XQJ_INMODECODE", "陕西 BOSS寻秦迹接入方式"),
    BOSS_SHANXI_XQJ_PASSWD("BOSS_SHANXI_XQJ_PASSWD", "陕西 BOSS寻秦迹密码"),

    //URL加密密钥
    ACTIVITY_URL_KEY("ACTIVITY_URL_KEY", "营销活动链接加密秘钥"),
    //营销模板 流量券
    LOTTERY_FLOWCARD_PATH("LOTTERY_FLOWCARD_PATH", "流量券手机号文件临时存储路径"),
    LOTTERY_FLOWCARD_URL("LOTTERY_FLOWCARD_URL", "流量券充值"),
    LOTTERY_FLOWCARD_VIRTUAL_URL("LOTTERY_FLOWCARD_VIRTUAL_URL", "流量券充值虚拟地址"),

    //二维码
    LOTTERY_QRCODE_PATH("LOTTERY_QRCODE_PATH", "二维码手机号文件临时存储路径"),
    QRCODE_DOWNLOAD_PATH("QRCODE_DOWNLOAD_PATH", "二维码文件临时存储路径"),
    LOTTERY_QRCODE_URL("LOTTERY_QRCODE_URL", "二维码充值url"),

    //陕西BOSS
    BOSS_SHANXI_CHARGEURL("BOSS_SHANXI_CHARGEURL", "陕西BOSS成员添加地址"),

    BOSS_FDN_APPKEY("BOSS_FDN_APPKEY", "网宿BOSS渠道APPKEY"),
    BOSS_FDN_APPSECRET("BOSS_FDN_APPSECRET", "网宿BOSS渠道APPSECRET"),
    BOSS_FDN_ORDER_URL("BOSS_FDN_ORDER_URL", "网宿BOSS渠道ORDERURL"),

    //unionflow渠道
    BOSS_UNIONFLOW_APPKEY("BOSS_UNIONFLOW_APPKEY", "Unionflow渠道的appkey"),
    BOSS_UNIONFLOW_APPSECRET("BOSS_UNIONFLOW_APPSECRET", "Unionflow渠道的appSecret"),
    BOSS_UNIONFLOW_CHARGEURL("BOSS_UNIONFLOW_CHARGEURL", "Unionflow渠道的充值地址"),

    BOSS_JIANGXI_APPSECRET("BOSS_JIANGXI_APPSECRET", "江西BOSS渠道APPSECRET"),
    BOSS_JIANGXI_SERVICEID("BOSS_JIANGXI_SERVICEID", "江西BOSS渠道SERVICEID"),
    BOSS_JIANGXI_ECCODE("BOSS_JIANGXI_ECCODE", "江西BOSS渠道ECCODE"),

    //运营商号段（前三位）
    CMCC_MOBILE_FLAG("CMCC_MOBILE_FLAG", "移动手机号号段前三位"),
    UNICOM_MOBILE_FLAG("UNICOM_MOBILE_FLAG", "联通手机号号段前三位"),
    TELECOM_MOBILE_FLAG("TELECOM_MOBILE_FLAG", "电信手机号号段前三位"),

    //批量赠送块大小
    BATCH_PRESENT_BLOCK_SIZE("BATCH_PRESENT_BLOCK_SIZE", "批量赠送的块大小"),

    //游客登录控制
    GUEST_LOGIN("GUEST_LOGIN", "游客登录控制"),
    GUEST_LOGIN_MSG("GUEST_LOGIN_MSG", "用户不存在"),

    FLOWCOIN_PRESENT_PATH("FLOWCOIN_PRESENT_PATH", "赠送流量币兑换网址"),

    //密码有效期
    PASSWORD_EXPIRE_TIME("PASSWORD_EXPIRE_TIME", "密码有效期时间"),

    //接口appkey及appsecret有效期
    INTERFACE_EXPIRE_TIME("INTERFACE_EXPIRE_TIME", "接口appkey及appsecret有效期时间"),

    //四川boss余额关停控制
    SC_ACCOUNT_BALANCE("SC_ACCOUNT_BALANCE", "四川平台企业关停的boss余额阈值"),
    SC_MOCK_ACCOUNT_BALANCE("SC_MOCK_ACCOUNT_BALANCE", "四川平台企业关停的boss余额阈值"),
    SC_MOCK_BOSS("SC_MOCK_BOSS","四川mockboss结果，包括查询余额和充值"),

    MAIL_ADDRESS("MAIL_ADDRESS", "发送邮箱地址"),

    //营销卡数量上下限
    MDRC_MINIMUM_NUM("MDRC_MINIMUN_NUM", "新建营销卡数量的最小值"),
    MDRC_MAXIMUM_NUM("MDRC_MAXIMUM_NUM", "新建营销卡数量的最大值"),

    //营销卡有效期配置项
    MDRC_VALID_MAX_DAYS("MDRC_VALID_MAX_DAYS", "营销卡有效期配置最大天数"),

    //山东云平台充值URL地址
    SD_CLOUD_URL("SD_CLOUD_URL", "山东云平台URL地址"),

    //山东云平台充值完整URL地址，方便测试组mock
    SD_CLOUD_CHARGE_URL("SD_CLOUD_CHARGE_URL", "山东云平台充值完整URL地址"),

    //山东云平台充值PLATFORMID
    SD_CLOUD_PLATFORMID("SD_CLOUD_PLATFORMID", "山东云平台充值platformid"),

    //山东充值默认的参数
    SD_BOSS_FEETYPE("SD_BOSS_FEETYPE", "山东充值参数feetype"),

    SD_BOSS_FACTFEE("SD_BOSS_FACTFEE", "山东充值参数factfee"),

    SD_BOSS_LIMITFLOW("SD_BOSS_LIMITFLOW", "山东充值参数limitflow"),

    SD_BOSS_ITEMID("SD_BOSS_ITEMID", "山东充值参数itemid"),

    SD_BOSS_STATUS("SD_BOSS_STATUS", "山东充值参数status"),

    //山东ftp服务器的相关参数
    SD_FTP_URL("SD_FTP_URL", "山东云平台ftp上传url"),

    SD_FTP_LOGINNAME("SD_FTP_LOGINNAME", "山东云平台ftp登录用户名"),

    SD_FTP_LOGINPASS("SD_FTP_LOGINPASS", "山东云平台ftp登录密码"),

    SD_FTP_FILEPATH("SD_FTP_FILEPATH", "山东云平台ftp文件路径"),


    //山东对账相关的参数
    SD_RECONCILE_BILL_PATH("SD_RECONCILE_BILL_PATH", "山东对账存放账单路径"),

    SD_RECONCILE_HUADAN_PATH("SD_RECONCILE_HUADAN_PATH", "山东对账存放话单路径"),

    SD_RECONCILE_CHANGERECORD_PATH("SD_RECONCILE_CHANGERECORD_PATH", "山东对账存放差异记录路径"),

    //山东Flow和用户对账相关的参数
    SD_RECONCILE_FLOWBILL_PATH("SD_RECONCILE_FLOWBILL_PATH", "山东流量池对账存放账单路径"),

    SD_RECONCILE_FLOWHUADAN_PATH("SD_RECONCILE_FLOWHUADAN_PATH", "山东流量池对账存放话单路径"),

    SD_RECONCILE_FLOWCHANGERECORD_PATH("SD_RECONCILE_FLOWCHANGERECORD_PATH", "山东流量池对账存放差异记录路径"),

    //山东Flow和boss对账相关路径
    SD_RECONCILE_FLOWBOSSBILL_PATH("SD_RECONCILE_FLOWBOSSBILL_PATH", "山东流量池boss对账存放账单路径"),

    SD_RECONCILE_FLOWBOSSHUADAN_PATH("SD_RECONCILE_FLOWBOSSHUADAN_PATH", "山东流量池boss对账存放话单路径"),

    SD_RECONCILE_FLOWBOSSCHANGERECORD_PATH("SD_RECONCILE_FLOWBOSSCHANGERECORD_PATH", "山东流量池boss对账存放差异记录路径"),

    SD_RECONCILE_NOTICE_URL("SD_RECONCILE_NOTICE_URL", "云平台上传通知路径"),

    //山东邮件相关参数
    SD_EMAIL_HOST("SD_EMAIL_HOST", "email服务器地址"),

    SD_EMAIL_SENDER("SD_EMAIL_SENDER", "email发送者"),

    SD_EMAIL_RECEIVER("SD_EMAIL_RECEIVER", "email接收者"),

    SD_EMAIL_USERNAME("SD_EMAIL_USERNAME", "email登录用户名"),

    SD_EMAIL_PASSWORD("SD_EMAIL_PASSWORD", "email登录用户密码"),

    SD_EMAIL_PORT("SD_EMAIL_PORT", "email服务器端口"),

    //山东方便测试的参数
    SD_NOUSE_FTP("SD_NOUSE_FTP", "不使用ftp上传下载文件,ok为不使用"),

    //山东方便测试组测试的定时任务参数
    SD_RECONCILE_FOR_TEST("SD_RECONCILE_FOR_TEST", "山东方便测试组测试的定时任务参数,ON为开启,对账频率为5分钟"),

    //山东对账完成是否发短信的功能
    SD_RECONCILE_EMAIL("SD_RECONCILE_EMAIL", "山东对账完成是否发邮件的功能,ON为开启"),

    //山东对账是否使用流水号
    SD_RECONCILE_USE_SEQ("SD_RECONCILE_USE_SEQ", "山东对账是否使用流水号,ON为开启"),

    //山东客户经理和企业关键人是否从云平台登录
    SD_LOGIN_ON_CLOUDPLATFORM("SD_LOGIN_ON_CLOUDPLATFORM", "山东客户经理和企业关键人是否从云平台登录，on为开启"),

    //山东DYNAMICTOKEN_UTL
    SD_DYNAMICTOKEN_UTL("SD_DYNAMICTOKEN_UTL", "山东DYNAMICTOKEN_UTL地址"),

    //山东充值是否开启异步
    SD_CHARGE_OPEN_ASYC("SD_CHARGE_OPEN_ASYC", "山东充值是否异步,on为启用"),

    //现金账户余额不足，是否需要告警
    ACCOUNT_ALERT_MSG("ACCOUNT_ALERT_MSG", "现金账户余额不足，是否需要短信通知,OK为启用，其它为不启用"),

    //EC白名单开关
    EC_IP_WHITELIST("EC_IP_WHITELIST", "EC接口ip白名单"),

    //普通赠送开关, ON为开启，其它为关闭
    PRESENT_SWITCH("PRESENT_SWITCH", "普通赠送开关"),

    //登录成功的频率限制， ON为开启， 其它为关闭
    LOGIN_SUCCESS_LIMIT("LOGIN_SUCCESS_LIMIT", "登录成功的频率限制，ON为开启，其它为关闭"),
    LOGIN_SUCCESS_LIMIT_RANGE("LOGIN_SUCCESS_LIMIT_RANGE", "登录成功的频率限制的时间范围，即以多长时间为限制"),
    LOGIN_SUCCESS_LIMIT_COUNT("LOGIN_SUCCESS_LIMIT_COUNT", "登录成功的频率限制的次数"),

    //登录失败的频率限制， ON为开启， 其它为关闭
    LOGIN_FAIL_LIMIT("LOGIN_FAIL_LIMIT", "登录失败的频率限制，ON为开启，其它为关闭"),
    LOGIN_FAIL_LIMIT_RANGE("LOGIN_FAIL_LIMIT_RANGE", "登录失败的频率限制的时间范围，即以多长时间为限制"),
    LOGIN_FAIL_LIMIT_COUNT("LOGIN_FAIL_LIMIT_COUNT", "登录失败的频率限制的次数"),

    //普通赠送频率限制， ON为开启， 其它为关闭
    PRESENT_RATE_LIMIT("PRESENT_RATE_LIMIT", "普通赠送的频率限制，ON为开启，其它为关闭"),
    PRESENT_RATE_LIMIT_RANGE("PRESENT_RATE_LIMIT_RANGE", "普通赠送的频率限制的时间范围，即以多长时间为限制"),
    PRESENT_RATE_LIMIT_COUNT("PRESENT_RATE_LIMIT_COUNT", "普通赠送的频率限制的次数"),
    PRESENT_SINGLE_RATE_LIMIT("PRESENT_SINGLE_RATE_LIMIT", "单个赠送的频率限制，ON为开启，其它为关闭"),
    PRESENT_SINGLE_RATE_LIMIT_RANGE("PRESENT_SINGLE_RATE_LIMIT_RANGE", "单个赠送的频率限制的时间范围，即以多长时间为限制"),
    PRESENT_SINGLE_RATE_LIMIT_COUNT("PRESENT_SINGLE_RATE_LIMIT_COUNT", "单个赠送的频率限制的次数"),

    //企业流控开关及流控短信开关
    ENTERPRISE_FLOW_CONTROL("ENTERPRISE_FLOW_CONTROL", "企业流控控制开关(OK-开启; 其余为关闭)"),
    ENT_FLOW_CONTROL_SMS_CMANAGER("ENT_FLOW_CONTROL_SMS_CMANAGER", "企业流控短信开关(客户经理)(OK-开启; 其余为关闭)"),
    ENT_FLOW_CONTROL_SMS_ADMINFORENTER("ENT_FLOW_CONTROL_SMS_ADMINFORENTER", "企业流控控制开关(企业管理员)(OK-开启; 其余为关闭)"),

    //流量卡充值失败后是否重新充值的开关
    MDRC_RECHARGE_WHEN_FAILED("MDRC_RECHARGE_WHEN_FAILED", "流量卡充值失败后是否重新充值的开关, ON为开启，没有或其它值为关闭"),

    //卓望省渠道队列
    ZHUOWANG_PROVINCE_PACKAGE_TIME("ZHUOWANG_PROVINCE_PACKAGE_TIME", "卓望渠道分省队列打包超时时间"),

    //验证充值流程,底层BOSS实现动态代理的标志
    DYNAMIC_PROXY_BOSS_FLAG("DYNAMIC_PROXY_BOSS_FLAG", "底层BOSS实现动态代理的标志"),

    //分发队列的消费者个数的配置项
    DELIVERQUEUE_CONSUMER_COUNT("DELIVERQUEUE_CONSUMER_COUNT", "分发队列的消费者个数"),

    //广东流量卡配置参数
    GD_CARD_BIZ_CODE("GD_CARD_BIZ_CODE", "广东流量卡的接口业务代码"),
    GD_CARD_SI_APPID("GD_CARD_SI_APPID", "广东流量卡的外围应用系统分配的公钥"),
    GD_CARD_APP_SYS_PUKEY("GD_CARD_APP_SYS_PUKEY", "广东流量卡的私钥"),
    GD_CARD_SUB_PRODUCT_CODE("GD_CARD_SUB_PRODUCT_CODE", "广东流量卡必须要带上的附加产品编码"),
    GD_CARD_SERVICE_CODE("GD_CARD_SERVICE_CODE", "广东流量卡必须要带上的服务编码"),

    //企业开户时，是否需要除了企业编码外的其它字段信息
    EXT_ENTERPRISE_INFO("EXT_ENTERPRISE_INFO", "是否需要扩展的企业信息字段, YES为需要，其它为不需要"),

    HLJ_FEE_SUPPLIER_ID("HLJ_FEE_SUPPLIER_ID", "黑龙江平台花费充值的供应商ID"),
    HLJ_FEE_GROUPACCNO("HLJ_FEE_GROUPACCNO", "黑龙江平台花费充值GROUPACCNO"),
    HLJ_FEE_GROUPNO("HLJ_FEE_GROUPNO", "黑龙江平台花费充值GROUPNO"),
    HLJ_FEE_APPKEY("HLJ_FEE_APPKEY", "黑龙江平台花费充值APPKEY"),

    //向上渠道相关参数
    BOSS_XS_PRIVATE_KEY("BOSS_XS_PRIVATE_KEY", "平台侧往向上公司请求时的加密私钥"),
    BOSS_XS_PUBLIC_KEY("BOSS_XS_PUBLIC_KEY", "平台侧接收向上公司响应时的解密公钥"),
    BOSS_XS_CHARGE_URL("BOSS_XS_CHARGE_URL", "向上渠道充值地址"),
    BOSS_XS_MAC_ID("BOSS_XS_MAC_ID", "向上渠道充值的macid"),

    //四川咪咕code
    SC_MIGU_CODE("SC_MIGU_CODE", "四川咪咕企业编码（不进行boss处的余额同步）"),


    GUANGDONG_ZHONGCHOU_CHECK_URL("GUANGDONG_ZHONGCHOU_CHECK_URL", "广东众筹验证手机号码的URL"),
    GUANGDONG_ZHONGCHOU_PAY_SECRET("GUANGDONG_ZHONGCHOU_PAY_SECRET", "广东众筹支付数字摘要的密钥"),
    GUANGDONG_ZHONGCHOU_PAY_URL("GUANGDONG_ZHONGCHOU_PAY_URL", "广东众筹支付URL"),
    GUANGDONG_ZHONGCHOU_PAY_BACK_URL("GUANGDONG_ZHONGCHOU_PAY_BACK_URL", "广东众筹支付完成页面通知地址"),
    GUANGDONG_ZHONGCHOU_PAY_NOTIFY_URL("GUANGDONG_ZHONGCHOU_PAY_NOTIFY_URL", "广东众筹支付完成后台通知地址"),
    GUANGDONG_QUERY_MOBILE_URL("GUANGDONG_QUERY_MOBILE_URL", "广东众筹查询手机号码的URL"),
    GUANGDONG_SEND_WX_MESSAGE_URL("GUANGDONG_SEND_WX_MESSAGE_URL", "广东众筹发送微信消息的URL"),
    GUANGDONG_SEND_WX_APPKEY("GUANGDONG_SEND_WX_APPKEY", "广东众筹发送微信消息的APPKEY"),
    GUANGDONG_SEND_WX_APPSECRET("GUANGDONG_SEND_WX_APPSECRET", "广东众筹发送微信消息的APPSECRET"),

    //广东众筹
    GUANGDONG_ZHONGCHOU_CHARGE_URL("GUANGDONG_ZHONGCHOU_CHARGE_URL", "广东众筹订购业务URL"),
    GUANGDONG_ZHONGCHOU_CHARGE_OPTTYPE("GUANGDONG_ZHONGCHOU_CHARGE_OPTTYPE", "广东众筹订购操作类型:0-开通"),
    GUANGDONG_ZHONGCHOU_CHARGE_USECYCLE("GUANGDONG_ZHONGCHOU_CHARGE_USECYCLE", "广东众筹订购使用的月数, 8585和8584产品必填"),
    GUANGDONG_ZHONGCHOU_CHARGE_EFFTYPE("GUANGDONG_ZHONGCHOU_CHARGE_EFFTYPE", "广东众筹订购生效方式,默认(0),立即(2),下月(3)"),
    GUANGDONG_ZHONGCHOU_LEC_ORDERRELATION_URL("GUANGDONG_ZHONGCHOU_LEC_ORDERRELATION_URL", "广东众筹大企业订购通知URL"),
    GUANGDONG_ZHONGCHOU_ORDERINFO_URL("GUANGDONG_ZHONGCHOU_ORDERINFO_URL", "广东众筹充值结果查询URL"),
    GUANGDONG_ZHONGCHOU_GETPAYMENTORDER_URL("GUANGDONG_ZHONGCHOU_GETPAYMENTORDER_URL", "广东众筹支付结果查询URL"),

    //产品转换关系类型
    PRODUCT_CONVERTER_TYPE("PRODUCT_CONVERTER_TYPE", "产品转化类型设置"),

    //虚拟产品大小限制
    MAX_SIZE_VIRTRUAL_MOBILE_FEE("MAX_SIZE_VIRTRUAL_MOBILE_FEE", "花费赠送单笔最大值(分)"),
    MAX_SIZE_VIRTRUAL_FLOW_PRODUCT("MAX_SIZE_VIRTRUAL_FLOW_PRODUCT", "流量池赠送单笔最大值(M)"),

    //辽宁渠道相关参数
    BOSS_LN_APP_ID("BOSS_LN_APP_ID", "辽宁渠道appId"),
    BOSS_LN_APP_KEY("BOSS_LN_APP_KEY", "辽宁渠道appKey"),
    BOSS_LN_CUST_ID("BOSS_LN_CUST_ID", "辽宁渠道客户编码"),
    BOSS_LN_BUSI_CODE("BOSS_LN_BUSI_CODE", "辽宁渠道集团编码"),
    BOSS_LN_EFFECTIVE_WAY("BOSS_LN_EFFECTIVE_WAY", "辽宁流量统付生效方式"),
    BOSS_LN_SEND_MSG("BOSS_LN_SEND_MSG", "辽宁渠道是否发送短信"),
    BOSS_LN_GIVE_MONTH("BOSS_LN_GIVE_MONTH", "辽宁渠道赠送月份"),
    BOSS_LN_OPENID("BOSS_LN_OPENID", "辽宁渠道Openid"),
    BOSS_LN_URL("BOSS_LN_URL", "辽宁渠道URL"),
    BOSS_LN_ACCESSTOKEN("BOSS_LN_ACCESSTOKEN", "辽宁渠道AccessToken"),
    BOSS_LN_OPERID("BOSS_LN_OPERID", "辽宁渠道OperId"),

    //天津BOSS
    TIANJIN_BOSS_URL("TIANJIN_BOSS_URL", "天津接口URL地址"),
    TIANJIN_BOSS_APPID("TIANJIN_BOSS_APPID", "天津接口APPID"),
    TIANJIN_BOSS_STATUS("TIANJIN_BOSS_STATUS", "天津接口STATUS,0:沙箱环境  1:为正式环境"),
    TIANJIN_BOSS_APPKEY("TIANJIN_BOSS_APPKEY", "天津接口APPKEY"),
    TIANJIN_BOSS_PUBLICKEY("TIANJIN_BOSS_PUBLICKEY", "天津接口公钥"),
    TIANJIN_BOSS_TRADEDEPARTID("TIANJIN_BOSS_TRADEDEPARTID", "天津接口工号部门编码"),
    TIANJIN_BOSS_TRADESTAFFID("TIANJIN_BOSS_TRADESTAFFID", "天津接口交易工号编码"),
    TIANJIN_BOSS_DEPARTID("TIANJIN_BOSS_DEPARTID", "天津接口部门编码"),
    TIANJIN_BOSS_TRADEDEPARTPASSWD("TIANJIN_BOSS_TRADEDEPARTPASSWD", "天津接口接入工号密码"),

    //审批流程短信通知
    APPROVAL_NOTICE("APPROVAL_NOTICE", "审批流程短信通知"),

    //内蒙古新BOSS
    BOSS_NM_EC_APPKEY("BOSS_NM_EC_APPKEY", "内蒙古BOSS的EC接口appkey"),
    BOSS_NM_EC_APPSECRET("BOSS_NM_EC_APPSECRET", "内蒙古BOSS的EC接口appsecret"),
    BOSS_NM_EC_CHARGE_URL("BOSS_NM_EC_CHARGE_URL", "内蒙古BOSS的EC接口CHARGE_URL"),
    BOSS_NM_EC_QUERY_URL("BOSS_NM_EC_QUERY_URL", "内蒙古BOSS的EC接口充值结果查询QUERY_URL"),
    BOSS_NM_EC_AUTH_URL("BOSS_NM_EC_AUTH_URL", "内蒙古BOSS的EC接口AUTH_URL"),

    //企业开户信息
    ENT_PROPS_INFO("ENT_PROPS_INFO", "企业开户所需要的字段信息"),

    //开放平台短信通道接入参数
    OPT_MSG_REQ_ADDR("OPT_MSG_REQ_ADDR", "开放平台短信通道请求地址"),
    OPT_MSG_APP_KEY("OPT_MSG_APP_KEY", "开放平台短信通道请求appkey"),
    OPT_MSG_SECRET_KEY("OPT_MSG_SECRET_KEY", "开放平台短信通道请求appsecret"),

    //开放平台短信通道查询地址
    OPT_MSG_QUERY_ADDR("OPT_MSG_QUERY_ADDR", "开放平台短信通道查询地址"),

    //广东众筹文件存储路径
    CROWD_FUNDING_PATH("CROWD_FUNDING_PATH", "广东众筹文件存储路径"),

    //广东众筹领取页面URL
    CROWD_FUNDING_GETFLOW_PAGE("CROWD_FUNDING_GETFLOW_PAGE", "广东众筹领取页面URL"),

    //广东众筹APPID
    CROWD_FUNDING_APP_ID("CROWD_FUNDING_APP_ID", "广东众筹微信公众号appID"),

    //广东众筹鉴权URL
    CROWD_FUNDING_AUTH_URL("CROWD_FUNDING_AUTH_URL", "广东众筹鉴权URL"),

    //广东众筹引导关注公众号URL
    CROWD_FUNDING_FOCUS_URL("CROWD_FUNDING_FOCUS_URL", "广东众筹引导关注公众号URL"),

    //广东众筹公众号绑定手机号URL
    CROWD_FUNDING_BINDED_URL("CROWD_FUNDING_BINDED_URL", "广东众筹公众号绑定手机号URL"),

    WEIXIN_CODE_URL("WEIXIN_CODE_URL", "微信公众号获取code接口"),
    WEIXIN_USERTYPE_URL("WEIXIN_USERTYPE_URL", "微信公众号获取用户类型及跳转链接接口"),
    WEIXIN_INVITE_QRCODE_URL("WEIXIN_INVITE_QRCODE_URL", "微信公众号获取邀请二维码接口"),
    WEIXIN_SEND_TEMPLATE_URL("WEIXIN_SEND_TEMPLATE_URL", "微信公众号发送模板消息接口"),
    WEIXIN_USERINFO_URL("WEIXIN_USERINFO_URL", "微信公众号获取用户信息接口"),
    WEIXIN_SCORE_EXCHANGE_RULE("WEIXIN_SCORE_EXCHANGE_RULE", "微信公众号积分兑换规则"),
    WEIXIN_EXCHANGE_MOTHLY_LIMIT("WEIXIN_EXCHANGE_MOTHLY_LIMIT", "微信公众号积分兑换账户每月兑换流量总额限制"),
    WEIXIN_LOTTERY_ENTER_ID("WEIXIN_LOTTERY_ENTER_ID", "广东微信大转盘活动所属企业id"),
    
    WEIXIN_EXCHANGE_DAY_LIMIT("WEIXIN_EXCHANGE_DAY_LIMIT", "微信公众号积分兑换账户每天兑换流量总额限制"),
    WEIXIN_EXCHANGE_NUM_LIMIT("WEIXIN_EXCHANGE_NUM_LIMIT", "微信公众号积分兑换账户每天兑换次数限制"),
    WEIXIN_EXCHANGE_PRODUCT_NUM_LIMIT("WEIXIN_EXCHANGE_PRODUCT_NUM_LIMIT", "微信公众号积分兑换产品兑换总额度"),
    WEIXIN_EXCHANGE_MOTHLY_ALL_LIMIT("WEIXIN_EXCHANGE_MOTHLY_ALL_LIMIT", "微信公众号积分兑换每月兑换总额度"),
    
    WEIXIN_EXCHANGE_START_DATE("WEIXIN_EXCHANGE_START_DATE", "微信公众号积分兑换每月限制开始日期"),
    WEIXIN_EXCHANGE_END_DATE("WEIXIN_EXCHANGE_END_DATE", "微信公众号积分兑换每月限制结束日期"),
    
    //海南FTP协议
    HAINAN_FTP_HOSTNAME("HAINAN_FTP_HOSTNAME", "海南FTP协议ip"),
    HAINAN_FTP_PORT("HAINAN_FTP_PORT", "海南FTP协议端口"),
    HAINAN_FTP_USERNAME("HAINAN_FTP_USERNAME", "海南FTP协议用户名"),
    HAINAN_FTP_PASSWORD("HAINAN_FTP_PASSWORD", "海南FTP协议用户密码"),

    //每日签到最大可获取的积分
    MAX_POINT_PER_DAY("MAX_POINT_PER_DAY", "每日签到最大可获取的积分"),
    //邀请好友可获得的积分
    INVITE_POINT("INVITE_POINT", "邀请好友可获得的积分"),

    //测试组
    TEST_RESULT_DESC("TEST_RESULT_DESC", "测试组自定义失败原因"),
    TEST_CHARGE_RESULT("TEST_CHARGE_RESULT", "测试组自定义充值结果"),

    //测试组
    EC_NEED_CHECK("NEED_CHECK", "ec接口contentType校验"),

    //四川集中化平台活动中奖校验手机号码URL
    JIZHONG_ACTIVITY_CHECK_URL("JIZHONG_ACTIVITY_CHECK_URL", "个人集中化平台校验号码url"),

    //四川个人流量红包，规则、活动名称、活动对象
    SC_REDPACKET_RULE("SC_REDPACKET_RULE", "四川个人流量红包活动规则"),
    SC_REDPACKET_NAME("SC_REDPACKET_NAME", "四川个人流量红包活动名称"),
    SC_REDPACKET_OBJECT("SC_REDPACKET_OBJECT", "四川个人流量红包活动对象"),
    //四川个人流量红包，订购限制
    SC_FLOW_ORDER_DAILY_LIMIT("SC_FLOW_ORDER_DAILY_LIMIT", "四川个人流量红包每天最多订购次数"),
    SC_FLOW_ORDER_MONTHLY_LIMIT("SC_FLOW_ORDER_MONTHLY_LIMIT", "四川个人流量红包每月最多订购次数"),
    //四川个人流量红包和生活单点登录接口参数
    SC_HSH_PARTNERID("SC_HSH_PARTNERID", "四川和生活合作者ID"),
    SC_HSH_SSO_URL("SC_HSH_SSO_URL", "四川和生活单点登录接口URL"),
    SC_HSH_APPID("SC_HSH_APPID", "四川和生活APPID"),
    SC_HSH_PUBLIC_KEY("SC_HSH_PUBLIC_KEY", "四川和生活的公钥路径"),
    SC_HSH_PRIVATE_KEY("SC_HSH_PRIVATE_KEY", "四川和生活的私钥路径"),

    //上海月呈渠道的参数
    SHYC_SUPPLIER_CODE("SHYC_SUPPLIER_CODE", "代理商编码"),
    SHYC_CHARGE_URL("SHYC_CHARGE_URL", "上海月呈充值地址"),
    SHYC_API_KEY("SHYC_API_KEY", "签名时使用的apikey"),

    //标识当前平台的营销活动是否可以指定三网产品, 只有当存在且值为YES的时候才允许,不存在或者值不为YES都不允许.
    ALL_PLATFORM_PRODUCT("ALL_PLATFORM_PRODUCT", "标识当前平台的营销活动是否可以三网产品"),

    //广东流量币BOSS
    BOSS_GUANGDONG_FLOWCOIN_ECCODE("BOSS_GUANGDONG_FLOWCOIN_ECCODE", "广东流量币BOSS通道ECCODE"),
    BOSS_GUANGDONG_FLOWCOIN_ECUSERNAME("BOSS_GUANGDONG_FLOWCOIN_ECUSERNAME", "广东流量币BOSS通道ECUSERNAME"),
    BOSS_GUANGDONG_FLOWCOIN_ECPASSWORD("BOSS_GUANGDONG_FLOWCOIN_ECPASSWORD", "广东流量币BOSS通道ECPASSWORD"),
    BOSS_GUANGDONG_FLOWCOIN_PRDORDNUM("BOSS_GUANGDONG_FLOWCOIN_PRDORDNUM", "广东流量币BOSS通道PRDORDNUM"),
    BOSS_GUANGDONG_FLOWCOIN_CHARGE_URL("BOSS_GUANGDONG_FLOWCOIN_CHARGE_URL", "广东流量币BOSS通道CHARGEURL"),

    //下载供应商列表文件临时目录
    SUPPLIER_PATH("SUPPLIER_PATH", "下载供应商列表文件临时目录"),

    //是否使用产品模板标示
    USE_PRODUCT_TEMPLATE("USE_PRODUCT_TEMPLATE", "是否使用产品模板"),

    //由于广东众筹和广东流量卡平台标示相同，所以采用这个标识区别企业开户差异
    IS_CROWDFUNDING_PLATFORM("IS_CROWDFUNDING_PLATFORM", "是否是广东众筹平台"),

    //吉林boss
    BOSS_JILIN_CHARGE_URL("BOSS_JILIN_CHARGE_URL", "吉林boss渠道充值地址"),
    BOSS_JILIN_OWEPAY_URL("BOSS_JILIN_OWEPAY_URL", "吉林boss渠道余额查询地址"),
    BOSS_JILIN_APPKEY("BOSS_JILIN_APPKEY", "吉林boss渠道APPKEY"),
    BOSS_JILIN_STATUS("BOSS_JILIN_STATUS", "吉林boss渠道STATUS"),
    BOSS_JILIN_USERNAME("BOSS_JILIN_USERNAME", "吉林boss渠道USERNAME"),
    BOSS_JILIN_PRIVATEKEY_FILE("BOSS_JILIN_PRIVATEKEY_FILE", "吉林boss渠道私钥文件"),
    BOSS_JILIN_TEMPLATEID("BOSS_JILIN_TEMPLATEID", "吉林短信模板id"),
    BOSS_JILIN_MSG_URL("BOSS_JILIN_TEMPLATEID", "吉林短信URL"),


    //北京云漫渠道参数
    BJYM_PARTY_ID("BJYM_PARTY_ID", "北京云漫渠道的partyId"),
    BJYM_KEY("BJYM_KEY", "北京云漫渠道的key"),
    BJYM_CHARGE_URL("BJYM_CHARGE_URL", "北京云漫渠道的充值请求地址"),
    BJYM_USER_NAME("BJYM_USER_NAME", "北京云漫渠道的用户名"),
    BJYM_CALLBACK_URL("BJYM_CALLBACK_URL", "接受北京云漫渠道回调的地址"),

    //生效方式
    EFFECT_TYPE("EFFECT_TYPE", "赠送页面是否需要生效方式"),
    
    //充值成功短信提醒
    CHARGE_SUCCESS_NOTICE("CHARGE_SUCCESS_NOTICE", "充值成功短信提醒"),
    CALLBACK_RETRY_TIMES("CALLBACK_RETRY_TIMES", "回调可以重复的次数"),
    CALLBACK_RETRY_SECONDS("CALLBACK_RETRY_SECONDS", "回调重试中间隔的时间种子"),

    //客户经理用户管理使用企业列表中的用户管理
    ADMIN_CHANGE_USE_ENTERLIST("ADMIN_CHANGE_USE_ENTERLIST","客户经理用户管理使用企业列表中的用户管理,true为使用"),
   
    //号码归属地
    PHONE_REGION("PHONE_REGION", "号码归属地"),
    NEED_CHECK_PHONE_REGION("NEED_CHECK_PHONE_REGION", "是否校验管理员归属地"),
    
    //是否需要静态密码、短信验证码结合的登录方式
    LOGIN_TYPE("LOGIN_TYPE", "登录方式：1静态密码，2短信验证码，3静态密码或短信验证码，4静态密码和短信验证码"),
    
    //天津流量平台接入
    BOSS_EC_TJ_APP_KEY("BOSS_EC_TJ_APP_KEY", "天津流量平台的appKey"),
    BOSS_EC_TJ_APP_SECRET("BOSS_EC_TJ_APP_SECRET", "天津流量平台的appSecret"),
    BOSS_EC_TJ_AUTH_URL("BOSS_EC_TJ_AUTH_URL", "天津流量平台的authUrl"),
    BOSS_EC_TJ_CHARGE_URL("BOSS_EC_TJ_CHARGE_URL", "天津流量平台的chargeUrl"),

    //本地文件存储服务路径
    LOCAL_FILESYSTEM_STORE_PATH("LOCAL_FILESYSTEM_STORE_PATH", "使用本地文件存储时的保存路径"),
    
    //支付配置
    PAY_ORIGINID("PAY_ORIGINID","支付平台的ORIGINID"),
    PAY_ACCOUNTCODE("PAY_ACCOUNTCODE","支付平台的ACCOUNTCODE"),
    PAY_MERCHANTID("PAY_MERCHANTID","支付平台的MERCHANTID"),
    PAY_PRODUCTID("PAY_PRODUCTID","支付平台的PRODUCTID"),
    PAY_PAYNOTIFYINTURL("PAY_PAYNOTIFYINTURL","支付平台的同步通知地址"),
    PAY_PAYNOTIFYPAGEURL("PAY_PAYNOTIFYPAGEURL","支付平台的异步通知地址"),
    PAY_PAYPERIOD("PAY_PAYPERIOD","支付平台的支付时间"),
    PAY_ENCODESECRET("PAY_ENCODESECRET","支付平台的加解密秘钥"),
    PAY_PAYPLATFORMURL("PAY_PAYPLATFORMURL","支付平台发送地址"),
    PAY_FORMREFUNDURL("PAY_FORMREFUNDURL","支付平台退款发送地址"),
    PAY_FORMREFUNDCALLBACKURL("PAY_FORMREFUNDCALLBACKURL","支付平台退款回调地址"),
    
    //云企信对接地址配置
    YQX_CONNECT_REQUEST_URL("YQX_CONNECT_REQUEST_URL" , "向云企信发送的请求地址"),
    YQX_CONNECT_RESPONSE_URL("YQX_CONNECT_RESPONSE_URL" , "给云企信返回的地址"),
    YQX_SC_CONNECT_RESPONSE_URL("YQX_SC_CONNECT_RESPONSE_URL" , "四川给云企信返回的地址"),
    YQX_CQ_CONNECT_RESPONSE_URL("YQX_CQ_CONNECT_RESPONSE_URL" , "重庆给云企信返回的地址"),
    YQX_SC_CONNECT_REQUEST_URL("YQX_SC_CONNECT_REQUEST_URL" , "向四川云企信发送的请求地址"),
    YQX_CQ_CONNECT_REQUEST_URL("YQX_CQ_CONNECT_REQUEST_URL" , "向重庆云企信发送的请求地址"),
    
    //云企信配置
    YQX_EC_APP_KEY("YQX_EC_APP_KEY", "云企信的appKey"),
    YQX_EC_APP_SECRET("YQX_EC_APP_SECRET", "云企信的appSecret"),
    YQX_EC_AUTH_URL("YQX_EC_AUTH_URL", "云企信的authUrl"),
    YQX_EC_CHARGE_URL("YQX_EC_CHARGE_URL", "云企信的chargeUrl"),
    YQX_ORDER_MONTH_LIMIT("YQX_ORDER_MONTH_LIMIT", "云企信订购用户每月订购次数限制"),
    YQX_SC_ORIGIN_ID("YQX_SC_ORIGIN_ID", "云企信四川厂商标识"),
    YQX_ORDERID_ENTER_CODE("YQX_ORDERID_ENTER_CODE", "云企信128位订单号企业编码"),
    YQX_ORDERID_PROVINCE_CODE("YQX_ORDERID_PROVINCE_CODE", "云企信128位订单号省份编码"),
    YQX_ORDERID_RECEIVE_MONEY("YQX_ORDERID_RECEIVE_MONEY", "云企信128位订单号收款方"),
    YQX_ORDERID_CITY_CODE("YQX_ORDERID_CITY_CODE", "云企信128位订单号地市编码"),
    YQX_ORDERID_ISP_CODE("YQX_ORDERID_ISP_CODE", "云企信128位订单号运营商编码"),
    YQX_ORDERID_SUPPLIER_CODE("YQX_ORDERID_SUPPLIER_CODE", "云企信128位订单号供应商编码"),
    YQX_ORDERID_APP_CODE("YQX_ORDERID_APP_CODE", "云企信128位订单号应用编码"),
    
    //云企信重庆
    YQX_CQ_CALLBACK_URL("YQX_CQ_CALLBACK_URL", "重庆云企信回调地址"),
    YQX_CQ_ORIGIN_ID("YQX_CQ_ORIGIN_ID", "云企信重庆厂商标识"),
    YQX_CQ_PRODUCT_NUM_LIMIT("YQX_CQ_PRODUCT_NUM_LIMIT", "重庆云企信产品个数限制"),
    YQX_ORDER_PAGE_TEXT("YQX_ORDER_PAGE_TEXT", "云企信订购页面展示的文案"),
    YQX_CQ_PHONECHECK("YQX_CQ_PHONECHECK", "云企信重庆移动校验"),
    
    YQX_MONTH_LAST_DAY_ORDER("YQX_MONTH_LAST_DAY_ORDER", "云企信月末最后一天是否可以订购的标识"),
    
    //云企信对账
    YQX_RECONCILE_IS_USE("YQX_RECONCILE_IS_USE","云企信是否使用对账,true为使用"),
    YQX_RECONCILE_IS_TEST("YQX_RECONCILE_IS_TEST","云企信是否测试服使用,true为使用，其它为生产环境使用，优先级在YQX_RECONCILE_IS_USE之后"),
    YQX_RECONCILE_FTP_URL("YQX_RECONCILE_FTP_URL","云企信对账ftp的url"),
    YQX_RECONCILE_FTP_PORT("YQX_RECONCILE_FTP_PORT","云企信对账ftp的port"),
    YQX_RECONCILE_FTP_LOGINNAME("YQX_RECONCILE_FTP_LOGINNAME","云企信对账ftp的username"),
    YQX_RECONCILE_FTP_LOGINPASS("YQX_RECONCILE_FTP_LOGINPASS","云企信对账ftp的pass"),
    YQX_RECONCILE_FTP_LOCALPATH("YQX_RECONCILE_FTP_LOCALPATH","云企信对账ftp的本地账单保存路径"),
    YQX_RECONCILE_FTP_TARGETPATH("YQX_RECONCILE_FTP_TARGETPATH","云企信对账ftp的目标文件保存路径"),
    YQX_RECONCILE_EMAIL_HOST("YQX_RECONCILE_EMAIL_HOST","email服务器"),
    YQX_RECONCILE_EMAIL_PORT("YQX_RECONCILE_EMAIL_PORT","email端口"),
    YQX_RECONCILE_EMAIL_SENDER("YQX_RECONCILE_EMAIL_SENDER","email发送邮箱"),
    YQX_RECONCILE_EMAIL_RECEIVER("YQX_RECONCILE_EMAIL_RECEIVER","email接收邮箱"),
    YQX_RECONCILE_EMAIL_USERNAME("YQX_RECONCILE_EMAIL_USERNAME","email用户名"),
    YQX_RECONCILE_EMAIL_PASS("YQX_RECONCILE_EMAIL_PASS","email用户密码"),
    
    //江苏对账
    JS_RECONCILE_IS_USE("JS_RECONCILE_IS_USE","江苏是否使用对账,true为使用"),
    JS_RECONCILE_IS_TEST("JS_RECONCILE_IS_TEST","江苏是否测试服使用,true为使用，其它为生产环境使用，优先级在JS_RECONCILE_IS_USE之后"),
    JS_RECONCILE_FTP_URL("JS_RECONCILE_FTP_URL","江苏对账ftp的url"),
    JS_RECONCILE_FTP_PORT("JS_RECONCILE_FTP_PORT","江苏对账ftp的port"),
    JS_RECONCILE_FTP_LOGINNAME("JS_RECONCILE_FTP_LOGINNAME","江苏对账ftp的username"),
    JS_RECONCILE_FTP_LOGINPASS("JS_RECONCILE_FTP_LOGINPASS","江苏对账ftp的pass"),
    JS_RECONCILE_FTP_LOCALPATH("JS_RECONCILE_FTP_LOCALPATH","江苏对账ftp的本地账单保存路径"),
    JS_RECONCILE_FTP_TARGETPATH("JS_RECONCILE_FTP_TARGETPATH","江苏对账ftp的目标文件保存路径"),
    JS_RECONCILE_EMAIL_HOST("JS_RECONCILE_EMAIL_HOST","江苏email服务器"),
    JS_RECONCILE_EMAIL_PORT("JS_RECONCILE_EMAIL_PORT","江苏email端口"),
    JS_RECONCILE_EMAIL_SENDER("JS_RECONCILE_EMAIL_SENDER","江苏email发送邮箱"),
    JS_RECONCILE_EMAIL_RECEIVER("JS_RECONCILE_EMAIL_RECEIVER","江苏email接收邮箱"),
    JS_RECONCILE_EMAIL_USERNAME("JS_RECONCILE_EMAIL_USERNAME","江苏email用户名"),
    JS_RECONCILE_EMAIL_PASS("JS_RECONCILE_EMAIL_PASS","江苏email用户密码"),
    JS_RECONCILE_FTP_REMOTEPATH("JS_RECONCILE_FTP_REMOTEPATH","江苏对账ftp的远程路径"),
    
    JS_OPENPLATFORM_FILE_PREFIX("JS_OPENPLATFORM_FILE_PREFIX","江苏开放平台对账生成文件前缀"),
    JS_OPENPLATFORM_FTP_URL("JS_OPENPLATFORM_FTP_URL","江苏开放平台对账ftp的url"),
    JS_OPENPLATFORM_FTP_PORT("JS_OPENPLATFORM_FTP_PORT","江苏开放平台对账ftp的port"),
    JS_OPENPLATFORM_FTP_LOGINNAME("JS_OPENPLATFORM_FTP_LOGINNAME","江苏开放平台对账ftp的LOGINNAME"),
    JS_OPENPLATFORM_FTP_LOGINPASS("JS_OPENPLATFORM_FTP_LOGINPASS","江苏开放平台对账ftp的LOGINPASS"),
    JS_OPENPLATFORM_FTP_LOCALPATH("JS_OPENPLATFORM_FTP_LOCALPATH","江苏开放平台对账ftp的本地账单保存路径"),
    JS_OPENPLATFORM_FTP_TARGETPATH("JS_OPENPLATFORM_FTP_TARGETPATH","江苏开放平台对账ftp的目标文件保存路径"),
    
    //供应商余额低于最小值时,是否开启短信通知
    NOTICE_BALANCE_NOT_ENOUGH("NOTICE_BALANCE_NOT_ENOUGH", "供应商余额低于最小值时,是否开启短信通知"),
    //供应商余额最小值
    SUPPLIER_MIN_BALANCE("SUPPLIER_MIN_BALANCE", "供应商余额最低值"),
    //供应商余额不足,通知指定角色管理员
    NOTICE_ROLE_ID("NOTICE_ROLE_ID", "供应商余额不足,通知指定角色管理员"),

    //企业关键人能否看到充值失败原因
    SHOW_FAIL_REASON_TO_ENT_MANAGER("SHOW_FAIL_REASON_TO_ENT_MANAGER", "是否给企业关键人显示充值失败原因, YES(忽略大小写)为显示, 此项缺失或设置为其它为不显示"),

    //江苏boss
    JS_BOSS_APPID("JS_BOSS_APPID", "江苏boss渠道appid"),
    JS_BOSS_ACCESS_TOKEN("JS_BOSS_ACCESS_TOKEN", "江苏boss渠道accessToken"),
    JS_BOSS_OPERATOR_ID("JS_BOSS_OPERATOR_ID", "江苏boss渠道operatorId"),
    JS_BOSS_CHARGE_URL("JS_BOSS_CHARGE_URL", "江苏boss渠道充值url"),
    

    //虚拟币最多赠送个数限制
    GIVE_VIRTUAL_COIN_MAX("GIVE_VIRTUAL_COIN_MAX", "虚拟币最多赠送个数限制"),

    //上海接口
    SH_BOSS_ENTER_CODE("SH_BOSS_ENTER_CODE", "上海boss企业编码"),
    SH_BOSS_ALERT_COUNT("SH_BOSS_ALERT_COUNT", "上海boss预警值"),
    SH_OLD_SUPPLIER_ID("SH_OLD_SUPPLIER_ID", "上海全网供应商id"),
    SH_NEW_SUPPLIER_ID("SH_NEW_SUPPLIER_ID", "上海本地供应商id"),

    //虚拟币最多赠送个数限制
    IS_BINDED_URL_IN_WEIXIN("IS_BINDED_URL_IN_WEIXIN", "判断新手机号在微信侧是否已经被绑定"),
    //修改微信侧手机号url
    MODIFY_MOBILE_URL_FOR_WEIXIN("MODIFY_MOBILE_URL_FOR_WEIXIN", "修改微信侧手机号url"),
    
    //江西boss
    BOSS_JIANGXI_SUPPLIERID("BOSS_JIANGXI_SUPPLIERID", "江西供应商id"),
    
    //上海newBoss
    BOSS_SHANGHAI_NEW_APPCODE("BOSS_SHANGHAI_NEW_APPCODE", "上海新boss渠道APPCODE"),
    BOSS_SHANGHAI_NEW_APK("BOSS_SHANGHAI_NEW_APK", "上海新boss渠道APK"),
    BOSS_SHANGHAI_NEW_SECURITY_URL("BOSS_SHANGHAI_NEW_SECURITY_URL", "上海新boss渠道securityUrl"),
    BOSS_SHANGHAI_NEW_OPENAPI_URL("BOSS_SHANGHAI_NEW_OPENAPI_URL", "上海新boss渠道openapiUrl"),
    BOSS_SHANGHAI_NEED_MOCK("BOSS_SHANGHAI_NEED_MOCK", "上海boss是否需要mock"),
    
    //向营销模板请求营销数据url
    ACTIVITY_GET_DATA_URL("ACTIVITY_GET_DATA_URL", "向营销模板请求营销数据url"),
    //删除营销模板侧运营数据url
    ACTIVITY_DEl_DATA_URL("ACTIVITY_DEl_DATA_URL", "删除营销模板侧运营数据url"),
    //签到
    START_TIME_OF_FORBID_TO_SIGN_IN("START_TIME_OF_FORBID_TO_SIGN_IN", "广东众筹禁止签到的起始时间"),
    END_TIME_OF_FORBID_TO_SIGN_IN("END_TIME_OF_FORBID_TO_SIGN_IN", "广东众筹禁止签到的结束始时间"),
    //最大签到次数，超过最大签到次数则不赠送流量币
    MAX_SERIAL_SIGN_DAY("MAX_SERIAL_SIGN_DAY", "超过最大签到次数则不赠送流量币"),
    //每天签到赠送流量币个数
    SIGN_GIVE_COUNT_PER_DAY("SIGN_GIVE_COUNT_PER_DAY", "每天签到赠送流量币个数"),
    //连续签到21天奖励流量币个数
    SIGN_AWARD_COUNT("SIGN_AWARD_COUNT", "连续签到21天奖励流量币个数"),
    //每天签到能获得流量币最大签到人数
    SIGN_MAX_COUNT_PER_DAY("SIGN_MAX_COUNT_PER_DAY", "每天签到能获得流量币最大签到人数"),
    EC_APPROVAL_NOTICE("EC_APPROVAL_NOTICE", "ec审批通知"),
    
    //营销活动向公众号请求用户手机号
    ACTIVITY_GET_MOBILE_FROM_WX_FLAG("ACTIVITY_GET_MOBILE_FROM_WX_FLAG", "营销活动向公众号请求用户手机号标志位"),
    ACTIVITY_GET_MOBILE_FROM_WX_URL("ACTIVITY_GET_MOBILE_FROM_WX_URL", "营销活动向公众号请求用户手机号URL"),


    //重庆套餐使用情况查询、流量使用情况查询、流量余额查询
    QRY_LEFT_TRAFFIC_URL("QRY_LEFT_TRAFFIC_URL", "重庆套餐剩余量信查询URL"),
    QRY_LEFT_TRAFFIC_CLIENT_ID("QRY_LEFT_TRAFFIC_CLIENT_ID", "重庆套餐剩余量信查询应用id"),
    QRY_LEFT_TRAFFIC_CLIENT_SECRET("QRY_LEFT_TRAFFIC_CLIENT_SECRET", "重庆套餐剩余量信查询应用秘钥"),
    QRY_LEFT_TRAFFIC_TOKEN_URL("QRY_LEFT_TRAFFIC_TOKEN_URL", "重庆套餐剩余量信查询获取token地址"),
    
    //重庆闲时流量包
    CQ_NEW_BOSS_URL("CQ_NEW_BOSS_URL", "重庆闲时流量包充值URL"),
    CQ_NEW_BOSS_CLIENT_ID("CQ_NEW_BOSS_CLIENT_ID", "重庆闲时流量包充值应用id"),
    CQ_NEW_BOSS_CLIENT_SECRET("CQ_NEW_BOSS_CLIENT_SECRET", "重庆闲时流量包充值应用秘钥"),
    CQ_NEW_BOSS_TOKEN_URL("CQ_NEW_BOSS_TOKEN_URL", "重庆闲时流量包充值获取token地址"),

    
    //广东单点登录配置
    GD_SSO_IS_USE("GD_SSO_IS_USE","广东是否使用单点登录"),
    GD_SSO_CHECKTOKEN_URL("GD_SSO_CHECKTOKEN_URL","广东单点登录检测token的地址"),
    GD_SSO_FIRSTPAGE_URL("GD_SSO_FIRSTPAGE_URL","广东单点登录首页的url"),
    GD_SSO_LOGAL_LOGIN_URL("GD_SSO_LOGAL_LOGIN_URL","广东平台本机登录url地址"),
    GD_SSO_PUBLIC_KEY("GD_SSO_PUBLIC_KEY","广东单点登录与登录平台共用加密key"),
    GD_SSO_PRIVATE_KEY("GD_SSO_PRIVATE_KEY","广东单点登录加密登录地址使用私钥"),
    GD_SSO_LOGOUT_URL("GD_SSO_LOGOUT_URL","广东单点登录登出时发给gdsso的url"),
    
    //广东接口
    GD_QRY_ENT_SRV_REG_URL("GD_QRY_ENT_SRV_REG_URL", "广东查询产品订购关系接口url"),
    GD_QRY_EC_SYNC_INFO_URL("GD_QRY_EC_SYNC_INFO_URL", "广东查询集团信息接口url"),
    GD_QRY_PRODUCT_FEE_URL("GD_QRY_PRODUCT_FEE_URL", "广东查询产品账户余额接口url"),
    GD_PLATFORM("GD_PLATFORM", "平台名称，8590众筹；8588流量卡"),

    
    //模糊显示
    BLUR_ENT_NAME("BLUR_ENT_NAME","企业名称模糊显示"),
    BLUR_ENT_CODE("BLUR_ENT_CODE","企业编码模糊显示"),
    BLUR_USER_NAME("BLUR_USER_NAME","用户名称模糊显示"),
    BLUR_USER_MOBILE("BLUR_USER_MOBILE","手机号码模糊显示"),
    BLUR_USER_EMAIL("BLUR_USER_EMAIL","邮箱模糊显示"),
    

    //当账户余额少于该值时从BOSS侧同步账户余额：始于重庆平台
    SYN_ACOUNT_FROM_BOSS_MIN_BALANCE("SYN_ACOUNT_FROM_BOSS_MIN_BALANCE", "当账户余额少于该值时从BOSS侧同步"),

    
    //营销卡一个手机号码单月的充值成功次数限制
    MAX_SIZE_CHARGE_SUCCESS_PER_MONTH("MAX_SIZE_CHARGE_SUCCESS_PER_MONTH", "营销卡一个手机号码单月的充值成功次数限制"),
    
    //account允许负数充值
    ACCOUNT_CHARGE_ALLOW_NEGATIVE("ACCOUNT_CHARGE_ALLOW_NEGATIVE", "false"),
    
    BOSS_SHANGHAI_OLD_SECURITY_URL("BOSS_SHANGHAI_OLD_SECURITY_URL", "上海全网boss渠道securityUrl"),
    BOSS_SHANGHAI_OLD_OPENAPI_URL("BOSS_SHANGHAI_OLD_OPENAPI_URL", "上海全网boss渠道openapiUrl"),
    BOSS_QUERY_TIME("BOSS_QUERY_TIME", "充值结果查询次数"),
    
    //江苏欧飞接口
    BOSS_JSOF_USERID("BOSS_JSOF_USERID", "江苏欧飞SP编码"),
    BOSS_JSOF_USERPWS("BOSS_JSOF_USERPWS", "江苏欧飞接入密码"),
    BOSS_JSOF_RETURL("BOSS_JSOF_RETURL", "江苏欧飞回调地址"),
    BOSS_JSOF_KEYSTRING("BOSS_JSOF_KEYSTRING", "江苏欧飞秘钥"),
    BOSS_JSOF_CHARGE_URL("BOSS_JSOF_CHARGE_URL", "江苏欧飞充值请求URL"),
    
    //包月赠送流量池最大输入值
    PRODUCT_SIZE_LIMIT("PRODUCT_SIZE_LIMIT", "包月赠送流量池最大输入值");
    
    private String key;
    private String description;

    GlobalConfigKeyEnum(String key, String description) {
        this.key = key;
        this.description = description;
    }

    public String getKey() {
        return key;
    }

    public String getDescription() {
        return description;
    }
}
