
package com.cmcc.vrp.boss.guangdongpool.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NGADCABServiceForOpen", targetNamespace = "http://adc.siinterface/")
@XmlSeeAlso({
    ObjectFactory.class
    })
public interface NGADCABServiceForOpen {



    /**
     * 
     * @param request
     * @return
     *     returns com.cmcc.vrp.boss.guangdongpool.wsdl.AdcSiResponse
     */
    @WebMethod(operationName = "AdcSiInterface", action = "http://adc.siinterface/AdcSiInterface")
    @WebResult(name = "AdcSiInterfaceResult", targetNamespace = "http://adc.siinterface/")
    @RequestWrapper(localName = "AdcSiInterface", targetNamespace = "http://adc.siinterface/", className = "com.cmcc.vrp.boss.guangdongpool.wsdl.AdcSiInterface")
    @ResponseWrapper(localName = "AdcSiInterfaceResponse", targetNamespace = "http://adc.siinterface/", className = "com.cmcc.vrp.boss.guangdongpool.wsdl.AdcSiInterfaceResponse")
    public AdcSiResponse adcSiInterface(
        @WebParam(name = "request", targetNamespace = "http://adc.siinterface/")
        AdcSiRequest request);

}
